import Foundation
import SwiftUI
import os

// MARK: - TranscriptSummary

/// Lightweight parsed representation of a transcript file.
/// Loaded once on init; full content is read lazily only when user taps Copy.
struct TranscriptSummary: Identifiable {
    let id = UUID()
    let url: URL
    let title: String
    let date: Date
    let duration: String   // e.g. "47:32"
    let speakerCount: Int
}

// MARK: - TranscriptLine

/// A single parsed line from the full transcript section.
/// Used by TranscriptDetailView to render styled transcript content.
struct TranscriptLine: Identifiable {
    let id = UUID()
    let timestamp: String?   // "00:12"
    let speaker: String?     // "Mic/You" or "System/Speaker 1"
    let text: String
}

// MARK: - TranscriptStore

/// Reads transcript .md files from the configured save directory and vends them
/// to TranscriptTrayView. Full file content is read only on copyableText(for:).
@available(macOS 14.0, *)
@MainActor
final class TranscriptStore: ObservableObject {

    @Published var transcripts: [TranscriptSummary] = []

    // MARK: - Init

    init() {
        refresh()
    }

    // MARK: - Public API

    /// Reload transcript list from disk (call after recording completes or on tray open).
    func refresh() {
        let dir = saveDirectory
        guard FileManager.default.fileExists(atPath: dir.path) else {
            if UserDefaults.standard.string(forKey: "transcriptSaveLocation") != nil {
                AppLogger.pipeline.warning("TranscriptStore: custom save directory not found", ["path": dir.path])
            }
            transcripts = []
            return
        }

        do {
            let files = try FileManager.default
                .contentsOfDirectory(at: dir, includingPropertiesForKeys: [.creationDateKey], options: [.skipsHiddenFiles])
                .filter { $0.pathExtension == "md" }
                .sorted { a, b in
                    let da = (try? a.resourceValues(forKeys: [.creationDateKey]).creationDate) ?? .distantPast
                    let db = (try? b.resourceValues(forKeys: [.creationDateKey]).creationDate) ?? .distantPast
                    return da > db
                }

            transcripts = files.prefix(10).compactMap { parseMetadata($0) }
        } catch {
            AppLogger.pipeline.error("TranscriptStore.refresh failed to read directory", ["path": dir.path, "error": "\(error)"])
            transcripts = []
        }
    }

    /// Returns clean, AI-ready text for a transcript.
    /// Strips YAML frontmatter and the analytics sections so the result can be
    /// pasted directly into Claude, ChatGPT, etc.
    func copyableText(for summary: TranscriptSummary) -> String? {
        guard let raw = try? String(contentsOf: summary.url, encoding: .utf8) else {
            AppLogger.pipeline.error("TranscriptStore.copyableText failed to read file", ["file": summary.url.lastPathComponent])
            return nil
        }

        var content = raw

        // 1. Strip YAML frontmatter (--- … ---)
        if content.hasPrefix("---"),
           let end = content.range(
               of: "\n---\n",
               range: content.index(content.startIndex, offsetBy: 3)..<content.endIndex
           ) {
            content = String(content[end.upperBound...])
        }

        // 2. Jump straight to the "## Full Transcript" section if present
        if let transcriptSection = content.range(of: "## Full Transcript\n") {
            content = String(content[transcriptSection.upperBound...])
        }

        // 3. Drop the trailing footer ("*Generated by…") and stray "---" separators
        let lines = content
            .components(separatedBy: "\n")
            .filter { !$0.hasPrefix("*Generated by") && $0 != "---" }

        let dialogue = lines
            .joined(separator: "\n")
            .trimmingCharacters(in: .whitespacesAndNewlines)

        // 4. Prepend a human-readable header
        let df = DateFormatter()
        df.dateStyle = .full
        df.timeStyle = .none
        let dateStr = df.string(from: summary.date)
        let durationStr = summary.duration.isEmpty ? "" : " | \(summary.duration)"

        return "\(summary.title) — \(dateStr)\(durationStr)\n\n\(dialogue)"
    }

    /// Parse transcript into structured lines for the detail view.
    /// Returns nil if the file can't be read.
    func displayLines(for summary: TranscriptSummary) -> [TranscriptLine]? {
        guard let raw = try? String(contentsOf: summary.url, encoding: .utf8) else {
            AppLogger.pipeline.error("TranscriptStore.displayLines failed to read file", ["file": summary.url.lastPathComponent])
            return nil
        }

        var content = raw

        // 1. Strip YAML frontmatter (--- … ---)
        if content.hasPrefix("---"),
           let end = content.range(
               of: "\n---\n",
               range: content.index(content.startIndex, offsetBy: 3)..<content.endIndex
           ) {
            content = String(content[end.upperBound...])
        }

        // 2. Jump to "## Full Transcript" section if present
        if let transcriptSection = content.range(of: "## Full Transcript\n") {
            content = String(content[transcriptSection.upperBound...])
        }

        // 3. Parse each line
        // Format: [MM:SS] [Source/Speaker] Text
        let linePattern = /^\[(\d{2}:\d{2})\]\s*\[([^\]]+)\]\s*(.+)$/
        var lines: [TranscriptLine] = []

        for rawLine in content.components(separatedBy: "\n") {
            let trimmed = rawLine.trimmingCharacters(in: .whitespaces)
            if trimmed.isEmpty || trimmed.hasPrefix("*Generated by") || trimmed == "---" { continue }

            if let match = trimmed.firstMatch(of: linePattern) {
                lines.append(TranscriptLine(
                    timestamp: String(match.1),
                    speaker: String(match.2),
                    text: String(match.3)
                ))
            } else if !trimmed.hasPrefix("#") && !trimmed.hasPrefix("*") {
                // Non-structured text (rare, but handle gracefully)
                lines.append(TranscriptLine(timestamp: nil, speaker: nil, text: trimmed))
            }
        }

        return lines
    }

    // MARK: - Save Directory

    private var saveDirectory: URL {
        if let custom = UserDefaults.standard.string(forKey: "transcriptSaveLocation"), !custom.isEmpty {
            return URL(fileURLWithPath: custom)
        }
        let docs = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
        return docs.appendingPathComponent("Transcripted")
    }

    // MARK: - Metadata Parsing

    /// Parse only the metadata needed for the tray row — does NOT load the full transcript.
    private func parseMetadata(_ url: URL) -> TranscriptSummary? {
        guard let raw = try? String(contentsOf: url, encoding: .utf8) else {
            AppLogger.pipeline.warning("TranscriptStore could not read file", ["file": url.lastPathComponent])
            return nil
        }

        var title = cleanFilenameTitle(url)
        var date: Date = fileCreationDate(url)
        var duration = ""
        var speakerCount = 0

        // Parse YAML frontmatter for structured fields
        if raw.hasPrefix("---"),
           let endRange = raw.range(
               of: "\n---\n",
               range: raw.index(raw.startIndex, offsetBy: 3)..<raw.endIndex
           ) {
            let yaml = String(raw[raw.index(raw.startIndex, offsetBy: 4)..<endRange.lowerBound])

            for line in yaml.components(separatedBy: "\n") {
                let parts = line.split(separator: ":", maxSplits: 1).map {
                    String($0).trimmingCharacters(in: .whitespaces)
                }
                guard parts.count == 2 else { continue }
                let key = parts[0]
                let val = parts[1].trimmingCharacters(in: CharacterSet(charactersIn: "\"' "))

                switch key {
                case "date":
                    let df = DateFormatter(); df.dateFormat = "yyyy-MM-dd"
                    if let d = df.date(from: val) {
                        date = d
                    } else {
                        AppLogger.pipeline.debug("TranscriptStore: malformed date in frontmatter", ["file": url.lastPathComponent, "value": val])
                    }
                case "duration":
                    duration = val
                case "mic_speakers", "system_speakers":
                    speakerCount += Int(val) ?? 0
                default:
                    break
                }
            }
        }

        // Prefer a markdown heading title over the filename
        for line in raw.components(separatedBy: "\n") {
            if line.hasPrefix("# ") {
                let candidate = String(line.dropFirst(2)).trimmingCharacters(in: .whitespaces)
                // Skip the generic "Call Recording — …" headings generated by TranscriptSaver
                if !candidate.lowercased().contains("call recording") && !candidate.lowercased().contains("meeting recording") {
                    title = candidate
                }
                break
            }
        }

        return TranscriptSummary(
            url: url,
            title: title,
            date: date,
            duration: duration,
            speakerCount: speakerCount
        )
    }

    private func cleanFilenameTitle(_ url: URL) -> String {
        let name = url.deletingPathExtension().lastPathComponent
        if name.hasPrefix("Call_") { return "Meeting" }
        return name
            .replacingOccurrences(of: "_", with: " ")
            .replacingOccurrences(of: "-", with: " ")
    }

    private func fileCreationDate(_ url: URL) -> Date {
        (try? url.resourceValues(forKeys: [.creationDateKey]).creationDate) ?? Date()
    }
}
