import Foundation

func testDictionaryPastMeetingFix() {
    let cloud = CustomDictionaryEntry(spoken: "cloud", replacement: "Claude")

    runSuite("DictionaryPastMeetingFix only rewrites spoken text") {
        let markdown = pastMeetingFixMarkdown()
        let result = DictionaryPastMeetingFix.replacing(cloud, in: markdown)

        assertEqual(result.count, 4, "every spoken cloud should be fixed, any case, like live transcription")
        assertTrue(result.markdown.contains("I asked Claude about it. Claude said yes."), "both matches on one line should change")
        assertTrue(result.markdown.contains("Cloudy weather, Claude storage."), "whole words only, matched without case like the live dictionary")
        assertTrue(result.markdown.contains("Then Claude's answer came back."), "a possessive still counts as the whole word")
        assertTrue(result.markdown.contains("title: \"Cloud sync review\""), "frontmatter must not change")
        assertTrue(result.markdown.contains("name: \"Cloud\""), "frontmatter speaker names must not change")
        assertTrue(result.markdown.contains("# Cloud sync review"), "the title heading must not change")
        assertTrue(result.markdown.contains("**00:12**  [System/Cloud]"), "speaker labels belong to the speaker editor")
        assertTrue(result.markdown.contains("*Generated by Transcripted with Parakeet (Cloud test)*"), "the footer must not change")
        assertEqual(
            result.markdown.components(separatedBy: "\n").count,
            markdown.components(separatedBy: "\n").count,
            "a fix must never add or remove lines"
        )
        assertEqual(DictionaryPastMeetingFix.fixCount(of: cloud, in: markdown), 4, "the count should match what a fix changes")
    }

    runSuite("DictionaryPastMeetingFix skips text that already reads right") {
        let casing = CustomDictionaryEntry(spoken: "PostHog", replacement: "PostHog")
        let markdown = "## Transcript\n\n[00:01] [Mic/You] We moved posthog to PostHog cloud.\n"
        let result = DictionaryPastMeetingFix.replacing(casing, in: markdown)
        assertEqual(result.count, 1, "the already-cased PostHog is not a fix")
        assertTrue(result.markdown.contains("We moved PostHog to PostHog cloud."), "the lowercase spot is re-cased")
        assertEqual(DictionaryPastMeetingFix.fixCount(of: casing, in: result.markdown), 0, "a fixed meeting has nothing left to fix")

        let longer = CustomDictionaryEntry(spoken: "claude", replacement: "Claude Code")
        let mixed = "## Transcript\n\n[00:01] [Mic/You] Claude Code and claude both ran.\n"
        let once = DictionaryPastMeetingFix.replacing(longer, in: mixed)
        assertEqual(once.count, 1, "text already reading Claude Code is left alone")
        assertTrue(once.markdown.contains("Claude Code and Claude Code both ran."), "a fix must not stack into Claude Code Code")
        assertEqual(DictionaryPastMeetingFix.replacing(longer, in: once.markdown).count, 0, "a second run changes nothing")
    }

    runSuite("DictionaryPastMeetingFix matches like the live dictionary") {
        let phrase = CustomDictionaryEntry(spoken: "okay ours", replacement: "OKRs")
        let markdown = "## Transcript\n\n[00:01] [Mic/You] Our okay   ours for Q3. Okay ourselves.\n"
        let result = DictionaryPastMeetingFix.replacing(phrase, in: markdown)
        assertEqual(result.count, 1, "extra spaces between words still match; a longer word does not")
        assertTrue(result.markdown.contains("Our OKRs for Q3. Okay ourselves."), "the phrase is replaced literally")

        let literal = CustomDictionaryEntry(spoken: "see plus plus", replacement: "C++ $1")
        let literalResult = DictionaryPastMeetingFix.replacing(literal, in: "## Transcript\n\n[00:01] [Mic/You] We use see plus plus.\n")
        assertTrue(literalResult.markdown.contains("We use C++ $1."), "$1 in the fix is literal text")
    }

    runSuite("DictionaryPastMeetingFix handles legacy inline turns and skips non-transcripts") {
        let legacy = """
        ---
        capture_type: meeting
        ---

        # Meeting Recording

        ## Full Transcript

        [00:01] [Mic/You] Hello cloud.

        [00:05] [System/[[Cloud]]] Cloud here.

        *Generated by Transcripted with Parakeet*
        """
        let result = DictionaryPastMeetingFix.replacing(cloud, in: legacy)
        assertEqual(result.count, 2, "text after the inline label should be fixed")
        assertTrue(result.markdown.contains("[00:05] [System/[[Cloud]]] Claude here."), "nested speaker links stay untouched")

        let notes = "---\ntitle: cloud notes\n---\n\nSome cloud notes with no transcript heading.\n"
        assertEqual(DictionaryPastMeetingFix.replacing(cloud, in: notes).count, 0, "files without a transcript heading are never touched")
        let unterminated = "---\ntitle: x\n\n## Transcript\n\ncloud\n"
        assertEqual(DictionaryPastMeetingFix.replacing(cloud, in: unterminated).count, 0, "unterminated frontmatter is never touched")
    }

    runSuite("DictionaryPastMeetingFix scans, fixes, and undoes across meetings") {
        withTemporaryPastMeetingDirectory { root in
            let first = root.appendingPathComponent("2026-09-20 Cloud sync review.md")
            let second = root.appendingPathComponent("2026-09-21 Standup.md")
            let clean = root.appendingPathComponent("2026-09-22 Clean.md")
            let summary = root.appendingPathComponent("2026-09-20 Cloud sync review.summary.md")
            let agentFile = root.appendingPathComponent("CLAUDE.md")
            let firstOriginal = pastMeetingFixMarkdown()
            let secondOriginal = "## Transcript\n\n**00:01**  [Mic/You]\nThe cloud build is green.\n"
            try firstOriginal.write(to: first, atomically: true, encoding: .utf8)
            try secondOriginal.write(to: second, atomically: true, encoding: .utf8)
            try "## Transcript\n\n**00:01**  [Mic/You]\nNothing to fix.\n".write(to: clean, atomically: true, encoding: .utf8)
            try "## Transcript\n\ncloud\n".write(to: summary, atomically: true, encoding: .utf8)
            try "## Transcript\n\ncloud\n".write(to: agentFile, atomically: true, encoding: .utf8)
            try FileManager.default.createDirectory(at: root.appendingPathComponent("audio"), withIntermediateDirectories: true)

            let okrs = CustomDictionaryEntry(spoken: "okay ours", replacement: "OKRs")
            let scans = DictionaryPastMeetingFix.scan(entries: [cloud, okrs], in: root)
            assertEqual(scans[cloud]?.meetingCount, 2, "both meetings that say cloud should be found")
            assertEqual(
                Set(scans[cloud]?.meetingURLs.map(\.lastPathComponent) ?? []),
                [first.lastPathComponent, second.lastPathComponent],
                "summary sidecars and agent files are not meetings"
            )
            assertNil(scans[okrs], "a correction with no past matches is left out")
            assertTrue(DictionaryPastMeetingFix.scan(entries: [cloud], in: root, isCancelled: { true }).isEmpty, "a cancelled scan reports nothing")

            let receipt = DictionaryPastMeetingFix.fix(cloud, meetingsAt: scans[cloud]?.meetingURLs ?? [])
            assertEqual(receipt.fixedCount, 2, "both meetings should be fixed")
            assertEqual(receipt.skippedCount, 0, "nothing was busy")
            assertTrue(try String(contentsOf: second, encoding: .utf8).contains("The Claude build is green."), "the fix is saved")
            assertNil(DictionaryPastMeetingFix.scan(entries: [cloud], in: root)[cloud], "a fixed library has nothing left to offer")

            // A later edit to one meeting must survive undo.
            let newer = try String(contentsOf: first, encoding: .utf8).replacingOccurrences(of: "[Mic/Linus]", with: "[Mic/Lionel]")
            try newer.write(to: first, atomically: true, encoding: .utf8)

            let undo = DictionaryPastMeetingFix.undo(receipt)
            assertEqual(undo.restoredURLs.map(\.lastPathComponent), [second.lastPathComponent], "only the untouched meeting is put back")
            assertEqual(undo.keptCount, 1, "the meeting edited since is kept")
            assertEqual(try String(contentsOf: second, encoding: .utf8), secondOriginal, "undo restores the file byte for byte")
            assertEqual(try String(contentsOf: first, encoding: .utf8), newer, "the newer edit must survive")

            let missing = DictionaryPastMeetingFix.fix(cloud, meetingsAt: [root.appendingPathComponent("gone.md")])
            assertEqual(missing.fixedCount, 0, "a missing meeting is not fixed")
            assertEqual(missing.skippedCount, 1, "a missing meeting is counted as skipped")
        }
    }

    runSuite("DictionaryPastMeetingFixCopy") {
        assertEqual(DictionaryPastMeetingFixCopy.found(1), "Also in 1 past meeting.")
        assertEqual(DictionaryPastMeetingFixCopy.found(6), "Also in 6 past meetings.")
        let url = URL(fileURLWithPath: "/tmp/meeting.md")
        let change = DictionaryPastMeetingFileChange(url: url, originalMarkdown: "", updatedMarkdown: "")
        assertEqual(
            DictionaryPastMeetingFixCopy.fixed(DictionaryPastMeetingFixReceipt(entry: cloud, changes: [change], skippedCount: 0)),
            "Fixed 1 meeting."
        )
        assertEqual(
            DictionaryPastMeetingFixCopy.fixed(DictionaryPastMeetingFixReceipt(entry: cloud, changes: [change, change], skippedCount: 1)),
            "Fixed 2 meetings. 1 was busy, so try again later."
        )
        assertEqual(
            DictionaryPastMeetingFixCopy.fixed(DictionaryPastMeetingFixReceipt(entry: cloud, changes: [], skippedCount: 2)),
            "Couldn\u{2019}t fix those meetings right now. Try again in a moment."
        )
        assertNil(DictionaryPastMeetingFixCopy.undone(DictionaryPastMeetingUndoResult(restoredURLs: [url], keptCount: 0)), "a clean undo needs no note")
        assertEqual(
            DictionaryPastMeetingFixCopy.undone(DictionaryPastMeetingUndoResult(restoredURLs: [], keptCount: 2)),
            "2 past meetings changed since, so they were kept."
        )
        assertEqual(
            DictionaryPastMeetingFixCopy.undone(DictionaryPastMeetingUndoResult(restoredURLs: [], keptCount: 1)),
            "1 past meeting changed since, so it was kept."
        )
    }
}

private func pastMeetingFixMarkdown() -> String {
    """
    ---
    title: "Cloud sync review"
    capture_id: "297F08B7-62AE-4291-9EA3-41EB0B17A64A"
    capture_type: meeting
    speakers:
      - id: "1"
        channel: system
        name: "Cloud"
        source: user_manual
    ---

    # Cloud sync review

    Recorded Apr 25, 2026 at 12:18 PM  •  31 sec  •  20 words  •  3 turns

    ## Transcript

    **00:00**  [Mic/Linus]
    I asked Cloud about it. Cloud said yes.

    **00:12**  [System/Cloud]
    Cloudy weather, cloud storage.

    **00:26**  [Mic/Linus]
    Then Cloud's answer came back.

    ---

    *Generated by Transcripted with Parakeet (Cloud test)*
    """
}

private func withTemporaryPastMeetingDirectory(_ body: (URL) throws -> Void) {
    let fm = FileManager.default
    let root = URL(fileURLWithPath: fm.currentDirectoryPath, isDirectory: true)
        .appendingPathComponent("build/dictionary-past-meeting-fix-tests", isDirectory: true)
        .appendingPathComponent(UUID().uuidString, isDirectory: true)
    do {
        try fm.createDirectory(at: root, withIntermediateDirectories: true)
        try body(root)
    } catch {
        assertTrue(false, "past meeting fix fixture failed: \(error)")
    }
    try? fm.removeItem(at: root)
}
