import Foundation

func testHomeMeetingWordFix() {
    runSuite("HomeMeetingWordFix only rewrites spoken text") {
        let markdown = wordFixStyledMeetingMarkdown()
        let result = HomeMeetingWordFix.replacing("Cloud", with: "Claude", in: markdown)

        assertEqual(result.count, 3, "every spoken Cloud should be counted, across turns")
        assertTrue(result.markdown.contains("I asked Claude about it. Claude said yes."), "both matches on one line should change")
        assertTrue(result.markdown.contains("Then Claude's answer came back."), "a possessive still counts as the whole word")
        assertTrue(result.markdown.contains("title: \"Cloud sync review\""), "frontmatter must not change")
        assertTrue(result.markdown.contains("name: \"Cloud\""), "frontmatter speaker names must not change")
        assertTrue(result.markdown.contains("# Cloud sync review"), "the title heading must not change")
        assertTrue(result.markdown.contains("**00:12**  [System/Cloud]"), "speaker labels belong to Name speakers, not Fix a word")
        assertTrue(result.markdown.contains("*Generated by Transcripted with Parakeet (Cloud test)*"), "the footer must not change")
        assertTrue(result.markdown.contains("Cloudy weather, cloud storage."), "whole-word, case-sensitive defaults leave these alone")
    }

    runSuite("HomeMeetingWordFix keeps the paragraph layout") {
        let markdown = wordFixStyledMeetingMarkdown()
        let result = HomeMeetingWordFix.replacing("Cloud", with: "Claude Code", in: markdown)
        assertEqual(
            result.markdown.components(separatedBy: "\n").count,
            markdown.components(separatedBy: "\n").count,
            "a fix must never add or remove lines"
        )
        let newlineFix = HomeMeetingWordFix.replacing("Cloud", with: "Claude\n\nnew paragraph", in: markdown)
        assertEqual(
            newlineFix.markdown.components(separatedBy: "\n").count,
            markdown.components(separatedBy: "\n").count,
            "a pasted newline in the replacement must not split a turn"
        )
        assertTrue(newlineFix.markdown.contains("I asked Claude new paragraph about it."), "newlines collapse to spaces")
    }

    runSuite("HomeMeetingWordFix options widen the match when asked") {
        let markdown = wordFixStyledMeetingMarkdown()
        let anyCase = HomeMeetingWordFixOptions(matchCase: false, wholeWords: true)
        assertEqual(HomeMeetingWordFix.matchCount(of: "Cloud", in: markdown, options: anyCase), 4, "match case off also finds lowercase cloud")

        let partial = HomeMeetingWordFixOptions(matchCase: true, wholeWords: false)
        assertEqual(HomeMeetingWordFix.matchCount(of: "Cloud", in: markdown, options: partial), 4, "whole words off also finds Cloudy")

        assertEqual(HomeMeetingWordFix.matchCount(of: "  ", in: markdown), 0, "an empty word matches nothing")
        assertEqual(HomeMeetingWordFix.matchCount(of: "Al", in: "## Transcript\n\n[00:01] [Mic/You] Alex and Al.\n"), 1, "Al should not match inside Alex")
    }

    runSuite("HomeMeetingWordFix treats regex characters literally") {
        let markdown = "## Transcript\n\n[00:01] [Mic/You] We use C++ and $5 plans. Also C.\n"
        let result = HomeMeetingWordFix.replacing("C++", with: "Swift $1", in: markdown, options: HomeMeetingWordFixOptions(matchCase: true, wholeWords: false))
        assertEqual(result.count, 1, "C++ is a literal, not a pattern")
        assertTrue(result.markdown.contains("We use Swift $1 and $5 plans."), "$1 in the replacement is literal text")
    }

    runSuite("HomeMeetingWordFix handles legacy inline turns") {
        let markdown = """
        ---
        capture_type: meeting
        ---

        # Meeting Recording

        ## Full Transcript

        [00:01] [Mic/You] Hello Alex.

        [00:05] [System/[[Alex]]] Alex here.

        *Generated by Transcripted with Parakeet*
        """
        let result = HomeMeetingWordFix.replacing("Alex", with: "Alexa", in: markdown)
        assertEqual(result.count, 2, "text after the inline label should be fixed")
        assertTrue(result.markdown.contains("[00:05] [System/[[Alex]]] Alexa here."), "nested speaker links stay untouched")
        assertTrue(result.markdown.contains("[00:01] [Mic/You] Hello Alexa."), "legacy lines keep their time and label")
    }

    runSuite("HomeMeetingWordFix writes the file and undoes it") {
        withTemporaryWordFixDirectory { root in
            let url = root.appendingPathComponent("2026-09-23 Cloud sync review.md")
            let original = wordFixStyledMeetingMarkdown()
            try original.write(to: url, atomically: true, encoding: .utf8)

            let receipt = try HomeMeetingWordFix.apply(find: "Cloud", replacement: "Claude", transcriptAt: url)
            assertEqual(receipt.count, 3, "the receipt should report how many spots changed")
            let saved = try String(contentsOf: url, encoding: .utf8)
            assertEqual(saved, receipt.updatedMarkdown, "the fix should be saved to the Markdown file")
            assertFalse(saved.contains("I asked Cloud"), "saved text should carry the fix")

            let outcome = HomeMeetingWordFix.perform(.undo(receipt), transcriptAt: url)
            assertEqual(outcome, .undone(receipt), "undo should succeed while nothing else touched the file")
            assertEqual(try String(contentsOf: url, encoding: .utf8), original, "undo should restore the file byte for byte")
        }
    }

    runSuite("HomeMeetingWordFix undo refuses to clobber a newer edit") {
        withTemporaryWordFixDirectory { root in
            let url = root.appendingPathComponent("meeting.md")
            try wordFixStyledMeetingMarkdown().write(to: url, atomically: true, encoding: .utf8)

            let receipt = try HomeMeetingWordFix.apply(find: "Cloud", replacement: "Claude", transcriptAt: url)
            let newer = receipt.updatedMarkdown.replacingOccurrences(of: "[Mic/Linus]", with: "[Mic/Lionel]")
            try newer.write(to: url, atomically: true, encoding: .utf8)

            let outcome = HomeMeetingWordFix.perform(.undo(receipt), transcriptAt: url)
            assertEqual(outcome, .failed(.changedSinceFix), "undo should stop when the file changed after the fix")
            assertEqual(try String(contentsOf: url, encoding: .utf8), newer, "the newer edit must survive")
        }
    }

    runSuite("HomeMeetingWordFix reports bad input without writing") {
        withTemporaryWordFixDirectory { root in
            let url = root.appendingPathComponent("meeting.md")
            let original = wordFixStyledMeetingMarkdown()
            try original.write(to: url, atomically: true, encoding: .utf8)

            let cases: [(HomeMeetingWordFixAction, HomeMeetingWordFixError)] = [
                (.replace(find: " ", replacement: "Claude", options: HomeMeetingWordFixOptions()), .emptyWord),
                (.replace(find: "Cloud", replacement: "\n", options: HomeMeetingWordFixOptions()), .emptyReplacement),
                (.replace(find: "Linus", replacement: "Lionel", options: HomeMeetingWordFixOptions()), .noMatches),
            ]
            for (action, expected) in cases {
                assertEqual(HomeMeetingWordFix.perform(action, transcriptAt: url), .failed(expected), "\(expected) should be reported")
            }
            assertEqual(try String(contentsOf: url, encoding: .utf8), original, "failed fixes must not touch the file")

            let missing = root.appendingPathComponent("missing.md")
            assertEqual(
                HomeMeetingWordFix.perform(.replace(find: "Cloud", replacement: "Claude", options: HomeMeetingWordFixOptions()), transcriptAt: missing),
                .failed(.readFailed),
                "a missing transcript should read as a read failure"
            )
        }
    }

    runSuite("HomeMeetingWordFixCopy") {
        assertEqual(HomeMeetingWordFixCopy.matchCount(0), "No matches")
        assertEqual(HomeMeetingWordFixCopy.matchCount(1), "1 match")
        assertEqual(HomeMeetingWordFixCopy.matchCount(4), "4 matches")
        let receipt = HomeMeetingWordFixReceipt(
            transcriptURL: URL(fileURLWithPath: "/tmp/meeting.md"),
            find: "Cloud",
            replacement: "Claude",
            count: 3,
            originalMarkdown: "",
            updatedMarkdown: ""
        )
        assertEqual(HomeMeetingWordFixCopy.fixed(receipt), "Changed \u{201C}Cloud\u{201D} to \u{201C}Claude\u{201D} in 3 spots.")
        assertEqual(HomeMeetingWordFixCopy.undone(receipt), "Put back \u{201C}Cloud\u{201D}.")
    }
}

private func wordFixStyledMeetingMarkdown() -> String {
    """
    ---
    title: "Cloud sync review"
    capture_id: "297F08B7-62AE-4291-9EA3-41EB0B17A64A"
    capture_type: meeting
    speakers:
      - id: "1"
        channel: system
        name: "Cloud"
        source: user_manual
    ---

    # Cloud sync review

    Recorded Apr 25, 2026 at 12:18 PM  •  31 sec  •  20 words  •  3 turns

    ## Transcript

    **00:00**  [Mic/Linus]
    I asked Cloud about it. Cloud said yes.

    **00:12**  [System/Cloud]
    Cloudy weather, cloud storage.

    **00:26**  [Mic/Linus]
    Then Cloud's answer came back.

    ---

    *Generated by Transcripted with Parakeet (Cloud test)*
    """
}

private func withTemporaryWordFixDirectory(_ body: (URL) throws -> Void) {
    let fm = FileManager.default
    let root = URL(fileURLWithPath: fm.currentDirectoryPath, isDirectory: true)
        .appendingPathComponent("build/home-meeting-word-fix-tests", isDirectory: true)
        .appendingPathComponent(UUID().uuidString, isDirectory: true)
    do {
        try fm.createDirectory(at: root, withIntermediateDirectories: true)
        try body(root)
    } catch {
        assertTrue(false, "word fix fixture failed: \(error)")
    }
    try? fm.removeItem(at: root)
}
