import Foundation

func testHomeMeetingPreviewFormatter() {
    runSuite("HomeMeetingPreviewFormatter parses current styled meeting markdown") {
        let content = HomeMeetingPreviewContent.make(from: styledMeetingMarkdown())

        assertEqual(content.transcriptLines.count, 4, "Styled transcript blocks should become readable rows")
        assertEqual(content.transcriptLines.first?.time, "00:00", "First row should keep the timestamp")
        assertEqual(content.transcriptLines.first?.speaker, "System/Speaker 1", "First row should keep the source/speaker label")
        assertTrue(
            content.transcriptLines.first?.text.hasPrefix("touch screen. Yeah.") == true,
            "Text on the line after the timestamp should be attached to the row"
        )
        assertFalse(content.fallbackText.contains("capture_id:"), "Preview fallback should not expose YAML metadata")
    }

    runSuite("HomeMeetingPreviewFormatter parses legacy inline transcript rows") {
        let content = HomeMeetingPreviewContent.make(from: legacyInlineMarkdown())

        assertEqual(content.transcriptLines.count, 2, "Legacy inline transcript rows should still preview cleanly")
        assertEqual(content.transcriptLines[0].text, "Hello there.", "Inline text should stay on the row")
        assertEqual(content.transcriptLines[1].speaker, "System/Alex", "Obsidian speaker links should be cleaned for preview")
    }
}

private func styledMeetingMarkdown() -> String {
    """
    ---
    title: "Meeting with Linus"
    capture_id: "297F08B7-62AE-4291-9EA3-41EB0B17A64A"
    capture_type: meeting
    total_word_count: 117
    ---

    # Meeting with Linus

    Recorded Apr 25, 2026 at 12:18 PM  •  31 sec  •  117 words  •  4 turns

    ## Transcript

    **00:00**  [System/Speaker 1]
    touch screen. Yeah. It actually is that it took us this long.

    **00:00**  [Mic/Linus]
    Yeah. It actually is and it took us a bit long to get to Or if we have

    **00:12**  [Mic/Linus]
    Oh

    **00:26**  [System/Linus]
    Dude, this is incredible. I'm honestly impressed.
    """
}

private func legacyInlineMarkdown() -> String {
    """
    ---
    capture_type: meeting
    ---

    # Meeting Recording

    ## Full Transcript

    [00:01] [Mic/You] Hello there.

    [00:05] [System/[[Alex]]] Nice to meet you.

    *Generated by Transcripted with Parakeet*
    """
}
