#!/usr/bin/env python3
"""Score dictation correction accuracy and emit score-dictation.json.

This measures how close the app's processed dictation output (dictionary
corrections + filler cleanup + punctuation) lands to a hand-written expected
output, over a fixture set of cases.

Inputs:
  --fixture   gold cases: {"items": [{"id": "...", "raw": "...", "expected": "..."}]}
  --candidate the app's output keyed by id: {"<id>": "<processed text>"}

The candidate is what the app actually produced — it must be generated by
driving dictation on the Mac (the raw field documents the input that produced
it). Without a candidate file this is INCOMPLETE, not a pass: we never invent
the app's output or re-implement product logic as a fake oracle here.

Per case: token-level accuracy = 1 - WER(expected, candidate). The board score
blends mean token accuracy with the exact-match rate.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


def tokenize(text: str) -> list[str]:
    return text.split()


def word_error_rate(expected: list[str], candidate: list[str]) -> float:
    """Levenshtein edit distance over tokens, normalized by reference length."""
    if not expected:
        return 0.0 if not candidate else 1.0
    prev = list(range(len(candidate) + 1))
    for i, e_tok in enumerate(expected, start=1):
        cur = [i]
        for j, c_tok in enumerate(candidate, start=1):
            cost = 0 if e_tok == c_tok else 1
            cur.append(min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + cost))
        prev = cur
    return prev[-1] / len(expected)


def score_cases(items: list[dict[str, Any]], candidate: dict[str, str]) -> dict[str, Any]:
    scored = 0
    exact = 0
    accuracy_sum = 0.0
    missing_candidates = 0
    for item in items:
        cid = str(item["id"])
        expected = str(item.get("expected", ""))
        if cid not in candidate:
            missing_candidates += 1
            continue
        produced = str(candidate[cid])
        wer = word_error_rate(tokenize(expected), tokenize(produced))
        accuracy_sum += max(0.0, 1.0 - wer)
        if produced.strip() == expected.strip():
            exact += 1
        scored += 1

    if scored == 0:
        return {"present": False, "detail": "no overlapping candidate ids", "missingCandidates": missing_candidates}

    mean_accuracy = accuracy_sum / scored
    exact_rate = exact / scored
    score = 100.0 * (0.7 * mean_accuracy + 0.3 * exact_rate)
    return {
        "present": True,
        "score": round(score, 1),
        "meanTokenAccuracy": round(mean_accuracy, 4),
        "exactMatchRate": round(exact_rate, 4),
        "scoredCases": scored,
        "missingCandidates": missing_candidates,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--fixture", required=True)
    parser.add_argument("--candidate", default="", help="App-produced output keyed by case id.")
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    out_path = Path(args.out).expanduser()
    out_path.parent.mkdir(parents=True, exist_ok=True)

    fixture = json.loads(Path(args.fixture).expanduser().read_text(encoding="utf-8"))
    items = fixture.get("items", [])

    if not args.candidate or not Path(args.candidate).expanduser().is_file():
        out_path.write_text(json.dumps({
            "board": "dictation", "metric": "correction-accuracy",
            "present": False, "score": None,
            "detail": "no candidate output supplied (drive dictation on the Mac to produce it)",
        }, indent=2, sort_keys=True), encoding="utf-8")
        print("INCOMPLETE: dictation correction needs candidate output")
        return 3

    candidate = json.loads(Path(args.candidate).expanduser().read_text(encoding="utf-8"))
    result = score_cases(items, candidate)
    present = result.get("present", False)
    score = result.get("score")
    detail = (
        f"token acc {result['meanTokenAccuracy']:.1%}, exact {result['exactMatchRate']:.0%} "
        f"over {result['scoredCases']} cases" if present else result.get("detail", "")
    )
    out_path.write_text(json.dumps({
        "board": "dictation", "metric": "correction-accuracy",
        "present": present, "score": score, "detail": detail, "subscores": result,
    }, indent=2, sort_keys=True), encoding="utf-8")
    print(f"dictation: {detail}")
    return 0 if present else 3


if __name__ == "__main__":
    raise SystemExit(main())
