import XCTest
@testable import Transcripted

@available(macOS 14.0, *)
final class TranscriptStoreTests: XCTestCase {

    private var tempDir: URL!

    override func setUp() {
        super.setUp()
        tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("TranscriptStoreTests_\(UUID())")
        try? FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
    }

    override func tearDown() {
        try? FileManager.default.removeItem(at: tempDir)
        super.tearDown()
    }

    // MARK: - copyableText

    @MainActor
    func testCopyableTextStripsYAMLFrontmatter() throws {
        let content = """
        ---
        date: "2026-03-01"
        duration: "12:34"
        ---
        ## Full Transcript
        [00:01] [Mic/You] Hello world
        [00:05] [System/Speaker 1] Hi there
        """
        let url = try writeTempMarkdown("test_copy.md", content: content)

        let store = TranscriptStore()
        let summary = TranscriptSummary(
            url: url,
            title: "Test Meeting",
            date: Date(),
            duration: "12:34",
            speakerCount: 2,
            speakerNames: ["You", "Speaker 1"],
            timeOfDay: nil
        )

        let text = store.copyableText(for: summary)
        XCTAssertNotNil(text)
        // Should NOT contain YAML delimiters
        XCTAssertFalse(text!.contains("---"))
        // Should contain the transcript lines
        XCTAssertTrue(text!.contains("[00:01]"))
        XCTAssertTrue(text!.contains("Hello world"))
    }

    @MainActor
    func testCopyableTextStripsGeneratedByFooter() throws {
        let content = """
        ---
        date: "2026-03-01"
        ---
        ## Full Transcript
        [00:01] [Mic/You] Hello
        *Generated by Transcripted*
        """
        let url = try writeTempMarkdown("test_footer.md", content: content)

        let store = TranscriptStore()
        let summary = TranscriptSummary(url: url, title: "Test", date: Date(), duration: "", speakerCount: 1, speakerNames: ["You"], timeOfDay: nil)

        let text = store.copyableText(for: summary)
        XCTAssertNotNil(text)
        XCTAssertFalse(text!.contains("Generated by"))
    }

    @MainActor
    func testCopyableTextIncludesHeader() throws {
        let content = """
        ---
        date: "2026-03-01"
        ---
        ## Full Transcript
        [00:01] [Mic/You] Test line
        """
        let url = try writeTempMarkdown("test_header.md", content: content)

        let store = TranscriptStore()
        let date = Date()
        let summary = TranscriptSummary(url: url, title: "Weekly Standup", date: date, duration: "05:30", speakerCount: 2, speakerNames: ["You", "Speaker 1"], timeOfDay: nil)

        let text = store.copyableText(for: summary)
        XCTAssertNotNil(text)
        // Header should contain the title and duration
        XCTAssertTrue(text!.hasPrefix("Weekly Standup"))
        XCTAssertTrue(text!.contains("05:30"))
    }

    // MARK: - displayLines

    @MainActor
    func testDisplayLinesParsesStructuredLines() throws {
        let content = """
        ---
        date: "2026-03-01"
        ---
        ## Full Transcript
        [00:12] [Mic/You] First utterance
        [00:45] [System/Speaker 1] Second utterance
        """
        let url = try writeTempMarkdown("test_lines.md", content: content)

        let store = TranscriptStore()
        let summary = TranscriptSummary(url: url, title: "Test", date: Date(), duration: "", speakerCount: 2, speakerNames: ["You", "Speaker 1"], timeOfDay: nil)

        let lines = store.displayLines(for: summary)
        XCTAssertNotNil(lines)
        XCTAssertEqual(lines!.count, 2)

        XCTAssertEqual(lines![0].timestamp, "00:12")
        XCTAssertEqual(lines![0].speaker, "Mic/You")
        XCTAssertEqual(lines![0].text, "First utterance")

        XCTAssertEqual(lines![1].timestamp, "00:45")
        XCTAssertEqual(lines![1].speaker, "System/Speaker 1")
        XCTAssertEqual(lines![1].text, "Second utterance")
    }

    @MainActor
    func testDisplayLinesSkipsEmptyAndMetaLines() throws {
        let content = """
        ---
        date: "2026-03-01"
        ---
        ## Full Transcript

        [00:01] [Mic/You] Only real line
        ---
        *Generated by Transcripted*
        """
        let url = try writeTempMarkdown("test_skip.md", content: content)

        let store = TranscriptStore()
        let summary = TranscriptSummary(url: url, title: "Test", date: Date(), duration: "", speakerCount: 1, speakerNames: ["You"], timeOfDay: nil)

        let lines = store.displayLines(for: summary)
        XCTAssertNotNil(lines)
        XCTAssertEqual(lines!.count, 1)
        XCTAssertEqual(lines![0].text, "Only real line")
    }

    @MainActor
    func testDisplayLinesHandlesUnstructuredText() throws {
        let content = """
        ---
        date: "2026-03-01"
        ---
        ## Full Transcript
        [00:01] [Mic/You] Structured line
        Some unstructured text that doesn't match the pattern
        """
        let url = try writeTempMarkdown("test_unstructured.md", content: content)

        let store = TranscriptStore()
        let summary = TranscriptSummary(url: url, title: "Test", date: Date(), duration: "", speakerCount: 1, speakerNames: ["You"], timeOfDay: nil)

        let lines = store.displayLines(for: summary)
        XCTAssertNotNil(lines)
        XCTAssertEqual(lines!.count, 2)
        // Unstructured line has nil timestamp and speaker
        XCTAssertNil(lines![1].timestamp)
        XCTAssertNil(lines![1].speaker)
        XCTAssertEqual(lines![1].text, "Some unstructured text that doesn't match the pattern")
    }

    // MARK: - Helpers

    @discardableResult
    private func writeTempMarkdown(_ filename: String, content: String) throws -> URL {
        let url = tempDir.appendingPathComponent(filename)
        try content.write(to: url, atomically: true, encoding: .utf8)
        return url
    }
}
