#!/usr/bin/env python3
"""Tests for the meeting-import bench adapter and make_meeting_suite.py.

Run: python3 scripts/hillclimb/benches/meeting_import.py --self-test

A fake transcripted-cli (a small Python script written to a temp dir) parses
the real import-audio flags, checks --speaker-db the way the real CLI does,
writes a transcript in the TranscriptFormatter.swift format, and prints the
real --json receipt shape, so everything runs on Linux without Swift.
"""

from __future__ import annotations

import hashlib
import io
import json
import os
import shutil
import subprocess
import sys
import tempfile
import textwrap
import unittest
import wave
from contextlib import redirect_stderr, redirect_stdout
from pathlib import Path
from unittest import mock

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent))

import make_meeting_suite  # noqa: E402
import meeting_import  # noqa: E402
from hc_benches import validate_result  # noqa: E402
from test_hc_proc import GrandchildMixin, grandchild_snippet  # noqa: E402

REPO = HERE.parents[2]
DEMO_CONFIG = HERE.parent / "fixtures" / "demo"
REAL_SUITE = REPO / "config" / "hillclimb" / "suites" / "meeting-corpus.json"
SECRET_WORD = "kenobi"

FAKE_CLI = r'''#!__PYTHON__
"""Fake transcripted-cli: import-audio and build-info, driven by <audio>.fake.json."""
import argparse, json, os, sqlite3, sys, time, uuid
from pathlib import Path

HERE = Path(__file__).resolve().parent

def build_info():
    path = HERE / "build-info.json"
    info = json.loads(path.read_text()) if path.exists() else {
        "diarization": True, "meetingImport": True, "mode": "meeting", "transcription": True}
    print(json.dumps(info, sort_keys=True, separators=(",", ":")))
    return 0

def db_info(path):
    info = {"path": path, "exists": os.path.isfile(path), "size": 0, "tables": None, "quick_check": None}
    if info["exists"]:
        info["size"] = os.path.getsize(path)
        con = sqlite3.connect(path)
        info["tables"] = con.execute("select count(*) from sqlite_schema").fetchone()[0]
        info["quick_check"] = con.execute("PRAGMA quick_check").fetchone()[0]
        con.close()
    return info

def transcript(control, audio):
    rows = control.get("rows", [["Speaker 0", "hello there"], ["Speaker 1", "general kenobi"]])
    words = sum(len(text.split()) for _, text in rows)
    speakers = sorted({label for label, _ in rows})
    capture = str(uuid.uuid4()).upper()
    lines = ["---", f'capture_id: "{capture}"', "capture_type: meeting", "format_version: 1",
             "transcript_style: raw", f'transcript_id: "{capture}"', "date: 2026-09-23", "time: 10:00"]
    if control.get("duration", "0:42") is not None:
        lines.append(f'duration: "{control.get("duration", "0:42")}"')
    lines += [f'processing_time: "{control.get("processing_time", "1.5s")}"',
              "transcription_engine: parakeet_local", "diarization_engine: pyannote_offline",
              "sources: [system]", "mic_utterances: 0", f"system_utterances: {len(rows)}",
              "mic_speakers: 0", f"system_speakers: {len(speakers)}", f"total_word_count: {words}",
              f'title: "{audio.stem}"', "speakers:"]
    for index, label in enumerate(speakers):
        lines += [f'  - id: "{index}"', "    channel: system", f'    name: "{label}"',
                  "    confidence: unknown", "    source: unknown"]
    lines += ["---", "", "# Meeting Recording - Sep 23, 2026", "",
              f"**Duration:** 0:42 | **Words:** {words} | **Utterances:** {len(rows)}", "",
              "---", "", "---", "", "## Channel & Speaker Analytics", "",
              "### Meeting Audio (Remote Participants)", f"- **Utterances:** {len(rows)}",
              f"- **Words:** ~{words}", "- **Speaking Time:** 0:40", f"- **Speakers Detected:** {len(speakers)}", "",
              "#### Remote Speaker Breakdown", ""]
    lines += [f"- **{label}:** 1 utterances, ~2 words, 0:10" for label in speakers]
    lines += ["", "---", "", "## Full Transcript", ""]
    for index, (label, text) in enumerate(rows):
        lines += [f"[00:{index * 5:02d}] [System/{label}] {text}", ""]
    lines += ["---", "", f"*Generated by Transcripted with Parakeet + PyAnnote (local) | Duration: 0:42 | {words} words | {len(speakers)} speakers*", ""]
    return "\n".join(lines)

def import_audio(argv):
    parser = argparse.ArgumentParser(prog="transcripted-cli import-audio")
    parser.add_argument("media_path")
    parser.add_argument("--output-dir")
    parser.add_argument("--title")
    parser.add_argument("--no-retain-audio", action="store_true")
    parser.add_argument("--no-speaker-identification", action="store_true")
    parser.add_argument("--speaker-db")
    parser.add_argument("--speaker-embedder", default="app", choices=["app", "wespeaker", "eres2net"])
    parser.add_argument("--models-dir")
    parser.add_argument("--diarization-models-dir")
    parser.add_argument("--no-download", action="store_true")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args(argv)
    audio = Path(args.media_path)
    control_path = audio.parent / (audio.name + ".fake.json")
    control = json.loads(control_path.read_text()) if control_path.exists() else {}
    knobs_file = os.environ.get("TRANSCRIPTED_LAB_KNOBS_FILE")
    record = {
        "argv": argv, "audio": audio.name, "speaker_db": db_info(args.speaker_db) if args.speaker_db else None,
        "env": {key: os.environ.get(key) for key in (
            "TRANSCRIPTED_DISABLE_FILE_LOGGER", "TRANSCRIPTED_SPEAKER_EMBEDDER", "TMPDIR",
            "TRANSCRIPTED_LAB_KNOBS_FILE")},
        "lab_knobs": json.loads(Path(knobs_file).read_text()) if knobs_file else None,
    }
    with (HERE / "calls.jsonl").open("a") as log:
        log.write(json.dumps(record) + "\n")
    if control.get("grandchild_pid_file"):
        # Like the real CLI's helper processes: a background child that must die with the group.
        __GRANDCHILD__
    marker = HERE / "models-loaded.marker"
    if not marker.exists():
        time.sleep(float(control.get("first_load", 0.6)))  # model load + CoreML compile
        marker.write_text("1")
    time.sleep(float(control.get("sleep", 0.02)))
    if args.speaker_db:
        info = record["speaker_db"]
        if not info["exists"]:
            print(f"Error: Speaker database not found: {args.speaker_db}", file=sys.stderr)
            return 64
        if info["size"] == 0:
            print("Error: The speaker database must be a nonempty regular file.", file=sys.stderr)
            return 1
    mode = control.get("mode", "ok")
    if knobs_file:
        if mode == "knob_reject":
            print("[lab-knobs] knobs file is not valid JSON; using defaults for every knob", file=sys.stderr)
        elif mode != "knob_silent":
            ids = ", ".join(sorted(record["lab_knobs"]))
            print(f"[lab-knobs] active overrides: {ids}", file=sys.stderr)
    if mode == "fail":
        print(f"Decoding {audio.name}", file=sys.stderr)
        print(f"Error: Input must be an existing regular audio/video file: /Users/someone/Private Calls/{audio.name}", file=sys.stderr)
        return 64
    out = Path(args.output_dir)
    out.mkdir(parents=True, exist_ok=True)
    capture = str(uuid.uuid4()).upper()
    path = out / f"2026-09-23_10-00-00 {audio.stem}_{capture.lower()}.md"
    if mode == "empty":
        control = dict(control, rows=[["Speaker 0", "..."]])
    if mode != "no_file":
        path.write_text(transcript(control, audio))
    receipt = {"captureID": capture, "transcriptPath": str(path)}
    # Swift's JSONEncoder with .sortedKeys escapes slashes and omits nil audioPath.
    print(json.dumps(receipt, sort_keys=True, separators=(",", ":")).replace("/", "\\/"))
    return 0

def main():
    if sys.argv[1:2] == ["build-info"]:
        return build_info()
    if sys.argv[1:2] == ["import-audio"]:
        return import_audio(sys.argv[2:])
    print("Error: unknown command", file=sys.stderr)
    return 64

sys.exit(main())
'''


def write_wav(path: Path, seconds: float, rate: int = 16_000) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    with wave.open(str(path), "wb") as handle:
        handle.setnchannels(1)
        handle.setsampwidth(2)
        handle.setframerate(rate)
        handle.writeframes(b"\x00\x00" * int(seconds * rate))
    return path


class Harness(unittest.TestCase):
    """Temp dir with a fake CLI, audio items, and a request writer."""

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.root = Path(self._tmp.name)
        self.bin_dir = self.root / "bin"
        self.bin_dir.mkdir()
        self.cli = self.bin_dir / "transcripted-cli"
        grandchild = textwrap.indent(grandchild_snippet('control["grandchild_pid_file"]'), " " * 8).strip()
        self.cli.write_text(FAKE_CLI.replace("__PYTHON__", sys.executable).replace("__GRANDCHILD__", grandchild))
        self.cli.chmod(0o755)
        self.audio_dir = self.root / "audio"
        self.work = self.root / "work"
        self.work.mkdir()

    def tearDown(self):
        self._tmp.cleanup()

    def item(self, item_id: str, *, seconds: float = 2.0, control: dict | None = None, **fields) -> dict:
        audio = write_wav(self.audio_dir / f"{item_id}.wav", seconds)
        if control is not None:
            (self.audio_dir / f"{item_id}.wav.fake.json").write_text(json.dumps(control))
        return {"id": item_id, "audio": str(audio), **fields}

    def truth(self, name: str, text: str) -> str:
        path = self.audio_dir / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        return str(path)

    def request(self, items: list[dict], *, knobs: dict | None = None, **options) -> dict:
        bench_options = {"cli_binary": str(self.cli), **options}
        return {
            "schema": "transcripted.hillclimb.request.v1",
            "trial_id": "t0001",
            "objective": "meeting-turnaround",
            "suite": "meeting-corpus",
            "split": "dev",
            "repetition": 0,
            "knobs": knobs or {},
            "items": items,
            "bench_options": bench_options,
            "result_path": str(self.work / "result.json"),
        }

    def run_bench(self, items: list[dict], **kwargs) -> dict:
        result = meeting_import.run_request(self.request(items, **kwargs))
        self.assertEqual(validate_result(result, [item["id"] for item in items]), [])
        self.assertEqual([row["id"] for row in result["items"]], [item["id"] for item in items])
        return result

    def calls(self) -> list[dict]:
        log = self.bin_dir / "calls.jsonl"
        return [json.loads(line) for line in log.read_text().splitlines()] if log.exists() else []

    def row(self, result: dict, item_id: str) -> dict:
        return next(row for row in result["items"] if row["id"] == item_id)


class MetricsTests(Harness):
    def test_turnaround_rtf_and_frontmatter_metrics(self):
        result = self.run_bench([self.item("m1", control={"sleep": 0.05}, duration_s=10.0)])
        row = self.row(result, "m1")
        metrics = row["metrics"]
        self.assertIsNone(row["error"])
        self.assertEqual(row["gates"], {"no_transcript": 0, "empty_transcript": 0})
        self.assertGreaterEqual(metrics["turnaround_s"], 0.05)
        self.assertAlmostEqual(metrics["turnaround_rtf"], metrics["turnaround_s"] / 10.0)
        self.assertEqual(metrics["audio_duration_s"], 10.0)
        self.assertEqual(metrics["pipeline_processing_s"], 1.5)
        self.assertEqual(metrics["transcript_words"], 4.0)
        self.assertEqual(metrics["speaker_count"], 2.0)
        self.assertNotIn("word_recall", metrics)  # no truth, no metric
        self.assertNotIn("speaker_count_error", metrics)

    def test_duration_falls_back_to_frontmatter_then_wave(self):
        result = self.run_bench([
            self.item("front", control={"duration": "1:02"}),
            self.item("wav", seconds=3.0, control={"duration": None}),
        ])
        self.assertEqual(self.row(result, "front")["metrics"]["audio_duration_s"], 62.0)
        self.assertAlmostEqual(self.row(result, "wav")["metrics"]["audio_duration_s"], 3.0)
        self.assertEqual(meeting_import.parse_clock("1:02:03"), 3723.0)
        self.assertEqual(meeting_import.parse_seconds("12.3s"), 12.3)

    def test_word_recall_reuses_compare_meeting_corpus(self):
        compare = meeting_import.compare_module()
        truth = self.truth("plain.txt", "Hello there, general Kenobi. You are a bold one")
        zoom = self.truth("zoom.txt", "[Alice] 00:00:01 hello there\n[Bob] 00:00:04\ngeneral kenobi\n")
        result = self.run_bench([self.item("plain", truth=truth), self.item("zoom", truth=zoom)])
        expected = compare.overlap_metrics(compare.tokenize(Path(truth).read_text()),
                                           ["hello", "there", "general", "kenobi"])["recall"]
        self.assertAlmostEqual(self.row(result, "plain")["metrics"]["word_recall"], expected)
        self.assertAlmostEqual(expected, 4 / 9)
        self.assertEqual(self.row(result, "zoom")["metrics"]["word_recall"], 1.0)

    def test_speaker_count_error(self):
        rows = [["Speaker 0", "a b"], ["Speaker 1", "c d"], ["Speaker 2", "e f"], ["Speaker 0", "g"]]
        result = self.run_bench([
            self.item("three", control={"rows": rows}, speakers=5),
            self.item("exact", speakers=2),
        ])
        self.assertEqual(self.row(result, "three")["metrics"]["speaker_count"], 3.0)
        self.assertEqual(self.row(result, "three")["metrics"]["speaker_count_error"], 2.0)
        self.assertEqual(self.row(result, "exact")["metrics"]["speaker_count_error"], 0.0)


class GateTests(GrandchildMixin, Harness):
    def test_gates_and_errors(self):
        truth_missing = str(self.audio_dir / "nope.txt")
        result = self.run_bench([
            self.item("fail", control={"mode": "fail"}),
            self.item("nofile", control={"mode": "no_file"}),
            self.item("empty", control={"mode": "empty"}),
            {"id": "noaudio", "audio": str(self.audio_dir / "missing.wav")},
            self.item("notruth", truth=truth_missing),
        ])
        fail = self.row(result, "fail")
        self.assertEqual(fail["gates"], {"no_transcript": 1, "empty_transcript": 0})
        self.assertEqual(fail["metrics"], {})
        self.assertIsNone(fail["error"])
        self.assertIn("exited 64", fail["detail"])
        self.assertNotIn("/Users", fail["detail"])
        self.assertNotIn("Private Calls", fail["detail"])
        self.assertEqual(self.row(result, "nofile")["gates"], {"no_transcript": 1, "empty_transcript": 0})
        empty = self.row(result, "empty")
        self.assertEqual(empty["gates"], {"no_transcript": 0, "empty_transcript": 1})
        self.assertEqual(empty["metrics"], {})
        self.assertIn("missing", self.row(result, "noaudio")["error"])
        self.assertIn("truth", self.row(result, "notruth")["error"])
        # Items that cannot be measured never start the CLI (1 warmup + 3 runs).
        self.assertEqual(len(self.calls()), 4)

    def test_timeout_is_no_transcript(self):
        result = self.run_bench([self.item("slow", control={"sleep": 2.0})], warmup=False, item_timeout_s=0.5)
        row = self.row(result, "slow")
        self.assertEqual(row["gates"]["no_transcript"], 1)
        self.assertIn("timed out", row["detail"])

    def test_timeout_kills_the_cli_process_group(self):
        pid_file = self.root / "grandchild.pid"
        control = {"sleep": 30.0, "first_load": 0.0, "grandchild_pid_file": str(pid_file)}
        result = self.run_bench([self.item("hang", control=control)], warmup=False, item_timeout_s=1.5)
        self.assertEqual(self.row(result, "hang")["gates"]["no_transcript"], 1)
        self.assert_grandchild_gone(pid_file)


class IsolationTests(Harness):
    def test_fresh_empty_speaker_db_every_run_and_env(self):
        with mock.patch.dict(os.environ, {"TRANSCRIPTED_SPEAKER_EMBEDDER": "eres2net"}):
            self.run_bench([self.item("a"), self.item("b")])
        calls = self.calls()
        self.assertEqual(len(calls), 3)
        paths = [call["speaker_db"]["path"] for call in calls]
        self.assertEqual(len(set(paths)), 3)
        for call in calls:
            db = call["speaker_db"]
            self.assertTrue(db["exists"])
            self.assertGreater(db["size"], 0)
            self.assertEqual(db["tables"], 0)
            self.assertEqual(db["quick_check"], "ok")
            self.assertEqual(call["env"]["TRANSCRIPTED_DISABLE_FILE_LOGGER"], "1")
            self.assertEqual(call["env"]["TRANSCRIPTED_SPEAKER_EMBEDDER"], "eres2net")
            self.assertTrue(Path(call["env"]["TMPDIR"]).is_absolute())
            argv = call["argv"]
            for flag in ("--no-retain-audio", "--no-download", "--json", "--output-dir"):
                self.assertIn(flag, argv)
            self.assertNotIn("--speaker-embedder", argv)
        self.assertFalse(any(Path(path).exists() for path in paths))

    def test_warmup_runs_shortest_item_untimed(self):
        long_item = self.item("long", seconds=4.0, duration_s=4.0)
        short_item = self.item("short", seconds=2.0, duration_s=2.0)
        result = self.run_bench([long_item, short_item])
        calls = self.calls()
        self.assertEqual([call["audio"] for call in calls], ["short.wav", "long.wav", "short.wav"])
        for row in result["items"]:
            self.assertLess(row["metrics"]["turnaround_s"], 0.5)  # the 0.6 s first load was not counted
        warmup = result["environment"]["warmup"]
        self.assertEqual((warmup["enabled"], warmup["ran"], warmup["item"], warmup["ok"], warmup["counted"]),
                         (True, True, "short", True, False))
        self.assertGreaterEqual(warmup["seconds"], 0.6)

    def test_without_warmup_first_item_pays_model_load(self):
        result = self.run_bench([self.item("first"), self.item("second")], warmup=False)
        self.assertEqual(len(self.calls()), 2)
        self.assertGreaterEqual(self.row(result, "first")["metrics"]["turnaround_s"], 0.6)
        self.assertEqual(result["environment"]["warmup"], {"enabled": False})

    def test_outputs_deleted_unless_kept(self):
        self.run_bench([self.item("c")])
        self.assertEqual(list(self.work.rglob("*.md")), [])
        self.assertEqual([p.name for p in self.work.iterdir()], [])
        with redirect_stderr(io.StringIO()):
            self.run_bench([self.item("d")], keep_outputs=True)
        self.assertEqual(len(list(self.work.rglob("*.md"))), 2)  # warmup + item


class KnobTests(Harness):
    def test_embedder_knob_and_model_dirs(self):
        self.run_bench([self.item("e")], knobs={"speaker.embedder": "eres2net"}, warmup=False,
                       models_dir="models/parakeet", diarization_models_dir=str(self.root / "diar"))
        argv = self.calls()[0]["argv"]
        self.assertEqual(argv[argv.index("--speaker-embedder") + 1], "eres2net")
        self.assertEqual(argv[argv.index("--models-dir") + 1], str(REPO / "models/parakeet"))
        self.assertEqual(argv[argv.index("--diarization-models-dir") + 1], str(self.root / "diar"))
        with self.assertRaises(meeting_import.BenchSetupError):
            meeting_import.run_request(self.request([self.item("f")], knobs={"speaker.embedder": "titanet"}))

    def test_lab_knobs_file(self):
        knobs = {"diarization.clustering_threshold": 0.62, "diarization.vbx_fa": 0.07,
                 "speaker.embedder": "wespeaker", "speech.parakeet.encoder_compute_units": "all"}
        result = self.run_bench([self.item("k")], knobs=knobs, warmup=False)
        call = self.calls()[0]
        self.assertEqual(call["lab_knobs"], {"diarization.clustering_threshold": 0.62, "diarization.vbx_fa": 0.07})
        self.assertEqual(Path(call["env"]["TRANSCRIPTED_LAB_KNOBS_FILE"]).parent, self.work.resolve())
        env = result["environment"]
        self.assertEqual(env["lab_knob_ids"], ["diarization.clustering_threshold", "diarization.vbx_fa"])
        self.assertEqual(env["ignored_knobs"], ["speech.parakeet.encoder_compute_units"])
        self.assertIsNone(self.row(result, "k")["error"])

    def test_lab_knobs_rejected_or_unconfirmed_errors_item(self):
        knobs = {"diarization.min_segment_duration": 0.5}
        result = self.run_bench([self.item("bad", control={"mode": "knob_reject"}),
                                 self.item("silent", control={"mode": "knob_silent"})], knobs=knobs, warmup=False)
        self.assertIn("not applied", self.row(result, "bad")["error"])
        self.assertIn("not confirmed", self.row(result, "silent")["error"])

    def test_no_lab_knobs_means_no_env_var(self):
        stale = str(self.root / "stale.json")
        with mock.patch.dict(os.environ, {"TRANSCRIPTED_LAB_KNOBS_FILE": stale}):
            result = self.run_bench([self.item("n")], knobs={"speaker.embedder": "app"}, warmup=False)
        self.assertIsNone(self.calls()[0]["env"]["TRANSCRIPTED_LAB_KNOBS_FILE"])
        self.assertEqual(result["environment"]["lab_knob_ids"], [])
        self.assertIsNone(self.row(result, "n")["error"])


class EnvironmentTests(Harness):
    def test_environment_identifies_binary_and_is_private(self):
        truth = self.truth("t.txt", f"hello there general {SECRET_WORD}")
        result = self.run_bench([self.item("p", truth=truth)])
        env = result["environment"]
        digest = hashlib.sha256(self.cli.read_bytes()).hexdigest()[:16]
        self.assertEqual(env["app_revision"], "sha256:" + digest)
        self.assertTrue(env["host"])
        self.assertTrue(env["os"])
        self.assertEqual(env["cli_build_info"]["meetingImport"], True)
        blob = json.dumps(result)
        self.assertNotIn(SECRET_WORD, blob.lower())
        self.assertNotIn(str(self.root), blob)

    def test_cli_without_meeting_import_is_refused(self):
        (self.bin_dir / "build-info.json").write_text(json.dumps({"meetingImport": False, "mode": "retrieval"}))
        with self.assertRaises(meeting_import.BenchSetupError):
            meeting_import.run_request(self.request([self.item("x")]))

    def test_missing_binary_exits_nonzero_via_main(self):
        request = self.request([self.item("y")])
        request["bench_options"]["cli_binary"] = str(self.root / "absent-cli")
        path = self.work / "request.json"
        path.write_text(json.dumps(request))
        completed = subprocess.run([sys.executable, str(HERE / "meeting_import.py"), "--request", str(path)],
                                   capture_output=True, text=True)
        self.assertEqual(completed.returncode, 2)
        self.assertIn("not found", completed.stderr)

    def test_main_writes_result_file(self):
        request = self.request([self.item("z")])
        path = self.work / "request.json"
        path.write_text(json.dumps(request))
        completed = subprocess.run([sys.executable, str(HERE / "meeting_import.py"), "--request", str(path)],
                                   capture_output=True, text=True)
        self.assertEqual(completed.returncode, 0, completed.stderr)
        result = json.loads(Path(request["result_path"]).read_text())
        self.assertEqual(validate_result(result, ["z"]), [])
        self.assertEqual(result["bench"], "meeting-import")


class SuiteBuilderTests(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.root = Path(self._tmp.name)

    def tearDown(self):
        self._tmp.cleanup()

    def corpus(self) -> Path:
        corpus = self.root / "meeting-corpus"
        manifest = []
        for index, labels in ((1, ("mic", "system")), (2, ("system",))):
            meeting_id = f"meeting-{index:04d}"
            audio = {}
            for label in labels:
                write_wav(corpus / meeting_id / f"{label}.wav", 2.0 + index)
                audio[label] = {"path": f"{label}.wav", "sha256": "x"}
            (corpus / meeting_id / "zoom.txt").write_text(
                "[Alice] 00:00:01 hello there\n[Bob] 00:00:04 general kenobi\n[Cara] 00:00:09 hi\n")
            manifest.append({"id": meeting_id, "audio": audio, "zoom_transcript": {"path": "zoom.txt"},
                             "speaker_names": ["Alice", "Bob"] if index == 1 else [], "duration_seconds": 99})
        (corpus / "manifest.json").write_text(json.dumps(manifest))
        return corpus

    def test_choose_track(self):
        a = write_wav(self.root / "a.wav", 1.0)
        b = write_wav(self.root / "b.wav", 1.0)
        choose = make_meeting_suite.choose_track
        self.assertEqual(choose({"mic": a, "system": b}, None)[0], "system")
        self.assertEqual(choose({"mic": a, "system": b}, "mic")[0], "mic")
        self.assertIsNone(choose({"mic": a}, "system"))
        self.assertEqual(choose({"mic": a, "gone": self.root / "gone.wav"}, None)[0], "mic")

    def test_corpus_items(self):
        corpus = self.corpus()
        items, skipped = make_meeting_suite.items_from_corpus(corpus, None, None)
        self.assertEqual(skipped, [])
        by_id = {item["id"]: item for item in items}
        self.assertEqual(sorted(by_id), ["meeting-0001", "meeting-0002"])
        first, second = by_id["meeting-0001"], by_id["meeting-0002"]
        self.assertTrue(first["audio"].endswith("meeting-0001/system.wav"))
        self.assertEqual(first["speakers"], 2)  # manifest speaker_names win
        self.assertEqual(second["speakers"], 3)  # parsed from the Zoom captions
        self.assertAlmostEqual(first["duration_s"], 3.0)
        self.assertTrue(Path(first["truth"]).is_file())
        only_mic, _ = make_meeting_suite.items_from_corpus(corpus, ["meeting-0001"], "mic")
        self.assertTrue(only_mic[0]["audio"].endswith("mic.wav"))
        with self.assertRaises(ValueError):
            make_meeting_suite.items_from_corpus(corpus, ["meeting-9999"], None)

    def test_folder_ids_are_content_hashes_and_stable(self):
        folder = self.root / "calls"
        write_wav(folder / "one.wav", 2.0)
        write_wav(folder / "sub" / "two.wav", 2.5)
        (folder / "one.txt").write_text("[Alice] 00:00:01 hi\n[Bob] 00:00:02 yo\n")
        items, _ = make_meeting_suite.items_from_folder(folder)
        moved = self.root / "elsewhere"
        shutil.copytree(folder, moved)
        moved_items, _ = make_meeting_suite.items_from_folder(moved)
        self.assertEqual(sorted(i["id"] for i in items), sorted(i["id"] for i in moved_items))
        by_name = {Path(item["audio"]).name: item for item in items}
        digest = hashlib.sha256((folder / "one.wav").read_bytes()).hexdigest()[:12]
        self.assertEqual(by_name["one.wav"]["id"], "clip-" + digest)
        self.assertEqual(by_name["one.wav"]["speakers"], 2)
        self.assertNotIn("truth", by_name["two.wav"])
        self.assertAlmostEqual(by_name["two.wav"]["duration_s"], 2.5)
        for item in items:
            self.assertNotIn("calls", item["id"])

    def test_items_file_loads_through_lab_suite(self):
        """The real suite file, its ~ items_file, and Lab.suite, with HOME pointed at a temp dir."""
        import hillclimb

        home = self.root / "home"
        corpus = self.corpus()
        config = self.root / "config"
        (config / "suites").mkdir(parents=True)
        for name in ("knobs.json", "objectives.json", "benches.json"):
            shutil.copy(DEMO_CONFIG / name, config / name)
        shutil.copy(REAL_SUITE, config / "suites" / REAL_SUITE.name)
        with mock.patch.dict(os.environ, {"HOME": str(home)}):
            with redirect_stdout(io.StringIO()):
                exit_code = make_meeting_suite.main(["--corpus-root", str(corpus)])
            self.assertEqual(exit_code, 0)
            items_path = make_meeting_suite.default_items_path()
            self.assertTrue(str(items_path).startswith(str(home)))
            suite = hillclimb.Lab(config, self.root / "state").suite("meeting-corpus")
        self.assertEqual(suite.salt, "meeting-corpus-v1")
        self.assertEqual(suite.holdout_fraction, 0.3)
        self.assertEqual(sorted(item["id"] for item in suite.items), ["meeting-0001", "meeting-0002"])
        self.assertEqual(sum(suite.counts().values()), 2)
        raw = json.loads(REAL_SUITE.read_text())
        self.assertEqual(raw["id"], "meeting-corpus")
        self.assertNotIn("items", raw)


if __name__ == "__main__":
    unittest.main()
