// ClipboardRestoringTextPaster+Pasteboard.swift
// The clipboard data layer: snapshot the user's clipboard (keeping privacy
// markers), put it back only when the borrowed text is still there, and copy
// plain text. Split out of ClipboardRestoringTextPaster.swift.

import AppKit
import Foundation

extension ClipboardRestoringTextPaster {
    struct PasteboardSnapshot {
        let items: [[NSPasteboard.PasteboardType: Data]]
        let isComplete: Bool
        /// True when any item carried an nspasteboard.org privacy marker
        /// (a password manager's concealed copy, a transient or auto-generated
        /// item). Such a clipboard is restored right after a paste as before,
        /// but never held on to for later.
        var containsPrivacyMarker = false
    }

    /// nspasteboard.org markers that say "don't keep this". Apps usually write
    /// them with empty data, so snapshots keep them even when empty.
    nonisolated static let privacyMarkerTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    /// nspasteboard.org marker for data an app puts on the clipboard only for a
    /// moment, like a paste done through Cmd+V. Clipboard managers skip items
    /// that carry it, so they neither record the dictation nor read it while it
    /// is borrowed (a read that would look like the target pasting).
    nonisolated static let transientPasteboardType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")

    @discardableResult
    func copyTextToClipboard(_ text: String, to pasteboard: any ClipboardPasteboard = NSPasteboard.general) -> Bool {
        pasteboard.clearContents()
        return pasteboard.setString(text, forType: .string)
            && pasteboard.string(forType: .string) == text
    }

    func snapshotPasteboardItems(
        from pasteboard: any ClipboardPasteboard,
        readData: (NSPasteboardItem, NSPasteboard.PasteboardType) -> Data? = { $0.data(forType: $1) }
    ) -> PasteboardSnapshot {
        var isComplete = true
        // This runs synchronously on the stop-to-paste path, so bound the whole
        // snapshot as well as each representation: one pathological clipboard
        // must not turn the stop into a multi-hundred-megabyte copy.
        var totalBytes = 0
        var containsPrivacyMarker = false
        let items: [[NSPasteboard.PasteboardType: Data]] = pasteboard.pasteboardItems?.map { item in
            var typeData: [NSPasteboard.PasteboardType: Data] = [:]
            var skippedTypes = 0
            for type in item.types {
                if Self.privacyMarkerTypes.contains(type) {
                    // Checked from the type list, before any data read, so a
                    // marker with no readable data still counts.
                    containsPrivacyMarker = true
                }
                // Once full, avoid asking additional lazy providers to allocate
                // data that cannot be retained. Individual provider fetches can
                // still exceed the budget; NSPasteboard has no size preflight.
                guard totalBytes < TranscriptedConstants.clipboardSnapshotMaxTotalBytes,
                      let data = readData(item, type),
                      data.count <= TranscriptedConstants.clipboardSnapshotMaxTypeBytes,
                      totalBytes + data.count <= TranscriptedConstants.clipboardSnapshotMaxTotalBytes else {
                    skippedTypes += 1
                    continue
                }
                // Keep empty privacy markers so a restored password stays
                // marked as concealed for clipboard managers.
                if !data.isEmpty || Self.privacyMarkerTypes.contains(type) {
                    typeData[type] = data
                    totalBytes += data.count
                }
            }
            // Dropping one heavy or unreadable representation (a screenshot's
            // TIFF next to its PNG) still restores the item, so it does not
            // block paste-back. Only an item that lost every representation
            // makes the snapshot incomplete — restoring it would erase the
            // user's clipboard, and that is the case paste-back refuses.
            if typeData.isEmpty, skippedTypes > 0 {
                isComplete = false
            }
            return typeData
        } ?? []
        return PasteboardSnapshot(
            items: items,
            isComplete: isComplete,
            containsPrivacyMarker: containsPrivacyMarker
        )
    }

    func restorePasteboardItems(
        _ savedItems: PasteboardSnapshot,
        temporaryString: String,
        temporaryChangeCount: Int,
        to pasteboard: any ClipboardPasteboard
    ) {
        restoreClipboardSnapshot(savedItems, matching: temporaryString,
            changeCount: temporaryChangeCount, to: pasteboard)
    }

    func restoreClipboardSnapshot(
        _ savedItems: PasteboardSnapshot, matching expectedString: String?,
        changeCount: Int, to pasteboard: any ClipboardPasteboard
    ) {
        guard savedItems.isComplete,
              pasteboard.changeCount == changeCount,
              pasteboard.string(forType: .string) == expectedString,
              pasteboard.changeCount == changeCount else { return }

        pasteboard.clearContents()
        let items = savedItems.items.map { typeData -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in typeData {
                item.setData(data, forType: type)
            }
            return item
        }
        if !items.isEmpty {
            pasteboard.writePasteboardItems(items)
        }
    }
}
