#!/bin/bash
# run-tests.sh — Compile and run Transcripted's fast utility test suite
# The fast test manifest is the source of truth for which root Tests/*.swift files run.

set -euo pipefail

ENTRYPOINT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$ENTRYPOINT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

MANIFEST="Tests/FastTests.manifest"
BUILD_DIR="build"
GENERATED_RUNNER="$BUILD_DIR/FastTestRunner.swift"

if [ ! -f "$MANIFEST" ]; then
    echo "Fast test manifest not found: $MANIFEST"
    exit 1
fi

manifest_entries=$(
    grep -v '^[[:space:]]*#' "$MANIFEST" | \
    sed '/^[[:space:]]*$/d'
)

if [ -z "$manifest_entries" ]; then
    echo "Fast test manifest is empty: $MANIFEST"
    exit 1
fi

manifest_files=$(
    printf '%s\n' "$manifest_entries" | \
    cut -d: -f1 | \
    sort
)

actual_files=$(
    find Tests -maxdepth 1 -name '*Tests.swift' -exec basename {} \; | \
    sort
)

if [ "$manifest_files" != "$actual_files" ]; then
    echo "Fast test manifest is out of sync with Tests/*.swift"
    echo ""
    echo "Manifest entries:"
    printf '%s\n' "$manifest_files"
    echo ""
    echo "Actual test files:"
    printf '%s\n' "$actual_files"
    exit 1
fi

mkdir -p "$BUILD_DIR"

cat > "$GENERATED_RUNNER" <<'EOF'
// Generated by run-tests.sh from Tests/FastTests.manifest.

import Foundation

@main
struct FastTestRunner {
    static func main() async {
        print("Transcripted Fast Test Suite\n")
EOF

while IFS=':' read -r test_file entry_function; do
    if [ -z "$test_file" ] || [ -z "$entry_function" ]; then
        echo "Malformed fast test manifest entry: ${test_file}:${entry_function}"
        exit 1
    fi

    if [ ! -f "Tests/$test_file" ]; then
        echo "Manifest references missing fast test file: Tests/$test_file"
        exit 1
    fi

    printf '        await runEntry(%s)\n' "$entry_function" >> "$GENERATED_RUNNER"
done <<EOF
$manifest_entries
EOF

cat >> "$GENERATED_RUNNER" <<'EOF'

        print("\n\(totalTests) tests, \(passedTests) passed, \(failedTests) failed")
        if failedTests > 0 {
            print("FAILED")
            exit(1)
        } else {
            print("ALL TESTS PASSED")
        }
    }

    static func runEntry(_ entry: () -> Void) async {
        entry()
    }

    static func runEntry(_ entry: () async -> Void) async {
        await entry()
    }
}
EOF

FAST_TEST_SOURCES=(
    "Tests/TestHelpers.swift"
    "$GENERATED_RUNNER"
)

while IFS=':' read -r test_file entry_function; do
    FAST_TEST_SOURCES+=("Tests/$test_file")
done <<EOF
$manifest_entries
EOF

APP_SOURCES=(
    "Sources/Support/TranscriptedPermissionKind.swift"
    "Sources/Support/TranscriptedPermissionAccess.swift"
    "Sources/Support/TranscriptedStoragePaths.swift"
    "Sources/Support/ClaudeDesktopIntegrationInstaller.swift"
    "Sources/Support/LaunchAtLoginPreferences.swift"
    "Sources/Support/MenuBarVisibilityPreferences.swift"
    "Sources/Support/PermissionsOnboardingPreferences.swift"
    "Sources/Support/HotkeyPreferences.swift"
    "Sources/Support/PhysicalDictationTriggerPreferences.swift"
    "Sources/Support/CustomDictionaryPreferences.swift"
    "Sources/Support/TranscriptionModelPreferences.swift"
    "Sources/Support/DictationAutoSendPreferences.swift"
    "Sources/Support/ClipboardRestoringTextPaster.swift"
    "Sources/Dictation/DictationSessionTimeout.swift"
    "Sources/Dictation/DictationStoragePaths.swift"
    "Sources/Dictation/DictationTranscriptWriter.swift"
    "Sources/Dictation/DictationTranscriptStore.swift"
    "Sources/Meeting/MeetingStoragePaths.swift"
    "Sources/Support/TranscriptedConstants.swift"
    "Sources/Speech/DictationInputDeviceSelectionPolicy.swift"
    "Sources/Speech/ParakeetModelInitDiagnostics.swift"
    "Sources/Speech/ParakeetPrewarmPolicy.swift"
    "Sources/Speech/ParakeetRecoveryState.swift"
    "Sources/Speech/ParakeetStartRecordingFailurePolicy.swift"
    "Sources/Speech/ParakeetShortAudioGate.swift"
    "Sources/Speech/DictationAudioRecovery.swift"
    "Sources/Speech/RecordedAudioTimeline.swift"
    "Sources/Meeting/MeetingRecordingStartGate.swift"
    "Sources/Meeting/MeetingFailureCopy.swift"
    "Sources/Meeting/MeetingFailureKind.swift"
    "Sources/Meeting/MeetingPromptDetector.swift"
    "Sources/Meeting/MeetingPromptHeuristics.swift"
    "Sources/Meeting/MeetingRecordingCleanup.swift"
    "Sources/Meeting/MeetingSessionUIPolicy.swift"
    "Sources/Meeting/MeetingWarmupStatusPolicy.swift"
    "Sources/Meeting/MeetingTranscriptStyler.swift"
    "Sources/Observability/AnalyticsReporter.swift"
    "Sources/Observability/AnalyticsEventPolicy.swift"
    "Sources/Observability/AnalyticsPayloadSanitizer.swift"
    "Sources/Observability/AnalyticsPreferences.swift"
    "Sources/Observability/CrashReportingPreferences.swift"
    "Sources/Observability/SentryRuntimeConfiguration.swift"
    "Sources/Observability/SentryEventPolicy.swift"
    "Sources/Observability/SentryPayloadSanitizer.swift"
    "Sources/Reliability/WakeRecoveryCoordinator.swift"
    "Sources/TranscriptedCore/Audio/MicRecordingSegment.swift"
    "Sources/TranscriptedCore/Models/SpeakerMapping.swift"
    "Sources/TranscriptedCore/Models/TranscriptionTypes.swift"
    "Sources/TranscriptedCore/Speaker/SpeakerProfile.swift"
    "Sources/TranscriptedCore/Speaker/SpeakerNamingPolicy.swift"
    "Sources/UI/Shared/AgentConnectionGuide.swift"
    "Sources/UI/Shared/FeedbackIssueBuilder.swift"
    "Sources/UI/Shared/FirstRunExperience.swift"
    "Sources/UI/Shared/AppSoundPlayer.swift"
    "Sources/UI/Shared/MeetingAudioArchiveResolver.swift"
    "Sources/UI/Shared/MeetingAudioPlayback.swift"
    "Sources/UI/Shared/RecentCaptureScanners.swift"
)

echo "Compiling tests..."
swiftc \
    "${FAST_TEST_SOURCES[@]}" \
    "${APP_SOURCES[@]}" \
    -framework AppKit \
    -framework AVFoundation \
    -framework ApplicationServices \
    -framework Carbon \
    -framework CoreMedia \
    -framework EventKit \
    -framework ScreenCaptureKit \
    -parse-as-library \
    -o build/tests \
    2>&1

echo "Running tests..."
echo ""
TRANSCRIPTED_DISABLE_FILE_LOGGER=1 ./build/tests
