#!/bin/bash
# run-tests.sh — Compile and run Transcripted's fast utility test suite
# The fast test manifest is the source of truth for which root Tests/*.swift files run.

set -euo pipefail

ENTRYPOINT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$ENTRYPOINT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

MANIFEST="Tests/FastTests.manifest"
BUILD_DIR="build"
GENERATED_RUNNER="$BUILD_DIR/FastTestRunner.$$.swift"
COVERAGE_DIR="$BUILD_DIR/coverage/fast-tests"
COVERAGE_PROFDATA="$COVERAGE_DIR/coverage.profdata"
COVERAGE_SUMMARY="$COVERAGE_DIR/summary.txt"
COVERAGE_LCOV="$COVERAGE_DIR/report.lcov"
COVERAGE_IGNORE_REGEX='(^|/)Tests/|(^|/)build/'

coverage_requested=false
coverage_env="${FAST_TEST_COVERAGE:-${TRANSCRIPTED_FAST_TEST_COVERAGE:-0}}"
case "$coverage_env" in
    1|true|TRUE|yes|YES)
        coverage_requested=true
        ;;
esac

for arg in "$@"; do
    case "$arg" in
        --coverage)
            coverage_requested=true
            ;;
        -h|--help)
            echo "Usage: bash run-tests.sh [--coverage]"
            echo ""
            echo "Set FAST_TEST_COVERAGE=1 or pass --coverage to write LLVM coverage artifacts to $COVERAGE_DIR."
            exit 0
            ;;
        *)
            echo "Unknown option: $arg"
            echo "Usage: bash run-tests.sh [--coverage]"
            exit 2
            ;;
    esac
done

cleanup_generated_runner() {
    rm -f "$GENERATED_RUNNER"
}
trap cleanup_generated_runner EXIT

if [ ! -f "$MANIFEST" ]; then
    echo "Fast test manifest not found: $MANIFEST"
    exit 1
fi

manifest_entries=$(
    grep -v '^[[:space:]]*#' "$MANIFEST" | \
    sed '/^[[:space:]]*$/d'
)

if [ -z "$manifest_entries" ]; then
    echo "Fast test manifest is empty: $MANIFEST"
    exit 1
fi

manifest_files=$(
    printf '%s\n' "$manifest_entries" | \
    cut -d: -f1 | \
    sort
)

actual_files=$(
    find Tests -maxdepth 1 -name '*Tests.swift' -exec basename {} \; | \
    sort
)

if [ "$manifest_files" != "$actual_files" ]; then
    echo "Fast test manifest is out of sync with Tests/*.swift"
    echo ""
    echo "Manifest entries:"
    printf '%s\n' "$manifest_files"
    echo ""
    echo "Actual test files:"
    printf '%s\n' "$actual_files"
    exit 1
fi

mkdir -p "$BUILD_DIR"

cat > "$GENERATED_RUNNER" <<'EOF'
// Generated by run-tests.sh from Tests/FastTests.manifest.

import Foundation

@main
struct FastTestRunner {
    static func main() async {
        print("Transcripted Fast Test Suite\n")
EOF

while IFS=':' read -r test_file entry_function; do
    if [ -z "$test_file" ] || [ -z "$entry_function" ]; then
        echo "Malformed fast test manifest entry: ${test_file}:${entry_function}"
        exit 1
    fi

    if [ ! -f "Tests/$test_file" ]; then
        echo "Manifest references missing fast test file: Tests/$test_file"
        exit 1
    fi

    printf '        await runEntry(%s)\n' "$entry_function" >> "$GENERATED_RUNNER"
done <<EOF
$manifest_entries
EOF

cat >> "$GENERATED_RUNNER" <<'EOF'

        print("\n\(totalTests) tests, \(passedTests) passed, \(failedTests) failed")
        if failedTests > 0 {
            print("FAILED")
            exit(1)
        } else {
            print("ALL TESTS PASSED")
        }
    }

    static func runEntry(_ entry: () -> Void) async {
        entry()
    }

    static func runEntry(_ entry: () async -> Void) async {
        await entry()
    }
}
EOF

FAST_TEST_SOURCES=(
    "Tests/TestHelpers.swift"
    "$GENERATED_RUNNER"
)

while IFS=':' read -r test_file entry_function; do
    FAST_TEST_SOURCES+=("Tests/$test_file")
done <<EOF
$manifest_entries
EOF

APP_SOURCES=(
    "Sources/Support/ActivationPolicyController.swift"
    "Sources/Support/TranscriptedPermissionKind.swift"
    "Sources/Support/TranscriptedPermissionAccess.swift"
    "Sources/Support/TranscriptedStoragePaths.swift"
    "Sources/Support/ClaudeDesktopIntegrationInstaller.swift"
    "Sources/Support/LaunchAtLoginPreferences.swift"
    "Sources/Support/MenuBarVisibilityPreferences.swift"
    "Sources/Support/PermissionsOnboardingPreferences.swift"
    "Sources/Support/HotkeyPreferences.swift"
    "Sources/Support/OnboardingDictationShortcutPolicy.swift"
    "Sources/Support/PhysicalDictationTriggerPreferences.swift"
    "Sources/Support/CustomDictionaryPreferences.swift"
    "Sources/Support/DockVisibilityPreferences.swift"
    "Sources/Support/MicrophoneProcessingPreferences.swift"
    "Sources/Support/QuitConfirmationPreferences.swift"
    "Sources/Support/AudioStoragePreferences.swift"
    "Sources/Support/LiveMeetingCodexPreferences.swift"
    "Sources/Support/TranscriptionModelPreferences.swift"
    "Sources/Support/ExistingInstallModelPrefetchPolicy.swift"
    "Sources/Support/ModelCacheInventory.swift"
    "Sources/Support/SingleInstanceGuard.swift"
    "Sources/Support/DictationAutoSendPreferences.swift"
    "Sources/Support/DictationCleanupPreferences.swift"
    "Sources/Support/DictationOverlayPresentationPreferences.swift"
    "Sources/Support/DictationFillerCleanupPolicy.swift"
    "Sources/Support/ClipboardRestoringTextPaster.swift"
    "Sources/Dictation/DictationSessionTimeout.swift"
    "Sources/Dictation/DictationStoragePaths.swift"
    "Sources/Dictation/DictationTranscriptWriter.swift"
    "Sources/Dictation/DictationTranscriptStore.swift"
    "Sources/Meeting/MeetingStoragePaths.swift"
    "Sources/Support/TranscriptedConstants.swift"
    "Sources/Speech/DictationInputDeviceSelectionPolicy.swift"
    "Sources/Speech/DictationReadinessWaitPolicy.swift"
    "Sources/Speech/ParakeetModelInitDiagnostics.swift"
    "Sources/Speech/ParakeetPrewarmPolicy.swift"
    "Sources/Speech/ParakeetRecoveryState.swift"
    "Sources/Speech/ParakeetStartRecordingFailurePolicy.swift"
    "Sources/Speech/ParakeetShortAudioGate.swift"
    "Sources/Speech/DictationAudioRecovery.swift"
    "Sources/Speech/RecordedAudioTimeline.swift"
    "Sources/Speech/DictationAudioLevelMeter.swift"
    "Sources/Meeting/MeetingRecordingStartGate.swift"
    "Sources/Meeting/MeetingCaptureSupport.swift"
    "Sources/Meeting/MeetingFailureExplanation.swift"
    "Sources/Meeting/MeetingFailureCopy.swift"
    "Sources/Meeting/MeetingFailureKind.swift"
    "Sources/Meeting/MeetingPromptDetector.swift"
    "Sources/Meeting/MeetingPromptHeuristics.swift"
    "Sources/Meeting/MeetingAudioInactivityDetector.swift"
    "Sources/Meeting/MeetingAudioStorageManager.swift"
    "Sources/Meeting/MeetingRecordingCleanup.swift"
    "Sources/Meeting/MeetingImportedAudioPreparer.swift"
    "Sources/Meeting/MeetingSessionUIPolicy.swift"
    "Sources/Meeting/MeetingWarmupStatusPolicy.swift"
    "Sources/Meeting/MeetingTranscriptStyler.swift"
    "Sources/Meeting/LiveMeetingCodexSession.swift"
    "Sources/Meeting/LiveMeetingStreamingUpdatePolicy.swift"
    "Sources/UI/MenuBar/MenuBarHeaderLayoutPolicy.swift"
    "Sources/Observability/AnalyticsReporter.swift"
    "Sources/Observability/LockedFileAppender.swift"
    "Sources/Observability/JSONLWriter.swift"
    "Sources/Observability/AnalyticsEventPolicy.swift"
    "Sources/Observability/ObservabilityTextRedactor.swift"
    "Sources/Observability/PayloadSanitizationCore.swift"
    "Sources/Observability/AnalyticsPayloadSanitizer.swift"
    "Sources/Observability/AnalyticsPreferences.swift"
    "Sources/Observability/CrashReportingPreferences.swift"
    "Sources/Observability/EventFileWritePolicy.swift"
    "Sources/Observability/LocalObservabilityPayloadSanitizer.swift"
    "Sources/Observability/ObservabilityEvent.swift"
    "Sources/Observability/ReliabilityPacketRecorder.swift"
    "Sources/Observability/RuntimeDiagnosticsStore.swift"
    "Sources/Observability/UpdateFailureKind.swift"
    "Sources/Observability/SentryRuntimeConfiguration.swift"
    "Sources/Observability/SentryEventPolicy.swift"
    "Sources/Observability/SentryPayloadSanitizer.swift"
    "Sources/Reliability/WakeRecoveryCoordinator.swift"
    "Sources/TranscriptedCore/Audio/MicRecordingSegment.swift"
    "Sources/TranscriptedCore/Models/SpeakerMapping.swift"
    "Sources/TranscriptedCore/Models/TranscriptionTypes.swift"
    "Sources/TranscriptedCore/Speaker/SpeakerProfile.swift"
    "Sources/TranscriptedCore/Speaker/SpeakerNamingPolicy.swift"
    "Sources/TranscriptedCore/Speaker/SpeakerPeopleReviewPolicy.swift"
    "Sources/TranscriptedCore/Storage/TranscriptFormatOptions.swift"
    "Sources/TranscriptedCore/Storage/TranscriptFrontmatter.swift"
    "Sources/Support/SpeakerNameSelectionPolicy.swift"
    "Sources/UI/Shared/AgentConnectionGuide.swift"
    "Sources/UI/Shared/FeedbackIssueBuilder.swift"
    "Sources/UI/Shared/SupportDiagnosticsBundle.swift"
    "Sources/UI/Shared/FirstRunExperience.swift"
    "Sources/UI/Shared/AppSoundPlayer.swift"
    "Sources/UI/Settings/TranscriptedSettingsPage.swift"
    "Sources/UI/Settings/SettingsRecentCaptureRefreshPolicy.swift"
    "Sources/UI/Settings/SettingsContentLayoutPolicy.swift"
    "Sources/UI/Settings/HomeDeleteConfirmationPolicy.swift"
    "Sources/UI/Settings/HomeFailedMeetingInlinePresentation.swift"
    "Sources/UI/Settings/HomeMeetingPreviewFormatter.swift"
    "Sources/UI/Overlay/DictationMeterPolicy.swift"
    "Sources/UI/Overlay/DictationCancelHintPolicy.swift"
    "Sources/UI/Overlay/DictationNoSpeechPresentationPolicy.swift"
    "Sources/UI/Overlay/DictationMicrophoneLoadingPresentationPolicy.swift"
    "Sources/UI/Overlay/DictationRecordingStartOverlayPolicy.swift"
    "Sources/UI/Shared/MeetingAudioArchiveResolver.swift"
    "Sources/UI/Shared/MeetingAudioPlayback.swift"
    "Sources/UI/Shared/RecentCaptureScanners.swift"
    "Sources/UI/Shared/SpeakerReviewQueueScanner.swift"
)

TEST_BINARY="$BUILD_DIR/tests"

if [ "$coverage_requested" = true ]; then
    mkdir -p "$COVERAGE_DIR"
    rm -f "$COVERAGE_DIR"/*.profraw "$COVERAGE_PROFDATA" "$COVERAGE_SUMMARY" "$COVERAGE_LCOV"
    TEST_BINARY="$COVERAGE_DIR/tests"
fi

echo "Compiling tests..."
SWIFTC_ARGS=(
    swiftc
)

if [ "$coverage_requested" = true ]; then
    SWIFTC_ARGS+=(
        -profile-generate
        -profile-coverage-mapping
    )
fi

SWIFTC_ARGS+=(
    "${FAST_TEST_SOURCES[@]}"
    "${APP_SOURCES[@]}"
    -framework AppKit
    -framework AVFoundation
    -framework ApplicationServices
    -framework Carbon
    -framework CoreMedia
    -framework EventKit
    -framework ScreenCaptureKit
    -parse-as-library
    -o "$TEST_BINARY"
)

"${SWIFTC_ARGS[@]}" 2>&1

echo "Running tests..."
echo ""

if [ "$coverage_requested" = true ]; then
    LLVM_PROFILE_FILE="$COVERAGE_DIR/default-%p.profraw" TRANSCRIPTED_DISABLE_FILE_LOGGER=1 "$TEST_BINARY"

    profraw_files=("$COVERAGE_DIR"/*.profraw)
    if [ ! -e "${profraw_files[0]}" ]; then
        echo "No LLVM profile data was written under $COVERAGE_DIR"
        exit 1
    fi

    llvm_profdata="${LLVM_PROFDATA:-}"
    if [ -z "$llvm_profdata" ]; then
        llvm_profdata="$(xcrun --find llvm-profdata)"
    fi

    llvm_cov="${LLVM_COV:-}"
    if [ -z "$llvm_cov" ]; then
        llvm_cov="$(xcrun --find llvm-cov)"
    fi

    echo ""
    echo "Writing coverage artifacts..."
    "$llvm_profdata" merge -sparse "${profraw_files[@]}" -o "$COVERAGE_PROFDATA"
    "$llvm_cov" report "$TEST_BINARY" \
        -instr-profile="$COVERAGE_PROFDATA" \
        -ignore-filename-regex="$COVERAGE_IGNORE_REGEX" \
        > "$COVERAGE_SUMMARY"
    "$llvm_cov" export "$TEST_BINARY" \
        -instr-profile="$COVERAGE_PROFDATA" \
        -format=lcov \
        -ignore-filename-regex="$COVERAGE_IGNORE_REGEX" \
        > "$COVERAGE_LCOV"

    echo "Coverage summary: $COVERAGE_SUMMARY"
    echo "Coverage LCOV: $COVERAGE_LCOV"
else
    TRANSCRIPTED_DISABLE_FILE_LOGGER=1 "$TEST_BINARY"
fi
