import Foundation
@testable import TranscriptedWritingCore

/// The fixed matrix behind the byte-identity proof for
/// `PreparedCompletionContext`: every typed context shape the cleaner
/// branches on, crossed with raw outputs that exercise each cleaning rule.
///
/// `goldenSignatures` was captured from the pre-refactor cleaner (the one
/// that re-tokenized the context on every call) and is checked in as
/// literal text, so the test compares the new path against the OLD path's
/// recorded behavior rather than against another call into itself. All of
/// it is synthetic: no personal writing, no model output.
enum PreparedContextGoldens {
    /// `nil` means "no typed context at all" — the request shape where the
    /// cleaner skips prefix trimming and context replay entirely.
    static let contexts: [String?] = [
        nil,
        "",
        "Sure, I will ",
        "That was ",
        "I am so sorry, I will be at the fun",
        "let me know if you need anything else, ",
        "we should ship it. ",
        "Hey I am ",
        "the meeting is at 3pm on Tuesday and the room is ",
        String(repeating: "the quick brown fox jumps over the lazy dog. ", count: 60) + "and then ",
    ]

    static let rawOutputs: [String] = [
        "",
        "   ",
        "<no_suggestion>",
        "\"<no_suggestion>\"",
        " I will try to get back to you",
        " try to get back to you",
        "Continuation: heading out now",
        "Candidate 1) sounds good to me",
        "As an AI language model, I cannot help",
        " let me know if you need anything else",
        " here, I am here.",
        " let me know let me know soon",
        " ready. It is not ready",
        "<think>hmm</think> on the way",
        "'quoted suggestion here'",
        " funeral home is on 5th",
        " going to be a long one\nsecond line dropped",
        " \u{200B}hidden zero width",
        " a b c d e f g h i j k",
        "ction next week",
        " the quick brown fox jumps",
    ]

    // MARK: - Scene-side matrix (echo + factual grounding)

    static let groundingTypedContext = "I will be there at "

    static let scenes: [ScreenScene.Scene?] = [
        nil,
        ScreenScene.Scene(mode: .composing, conversationTurns: [], referenceSnippets: []),
        ScreenScene.Scene(
            mode: .replying,
            conversationTurns: [
                ScreenScene.ConversationTurn(speaker: .other, text: "are you still coming tonight"),
                ScreenScene.ConversationTurn(speaker: .selfSpeaker, text: "yes, I will be there at 7pm"),
            ],
            referenceSnippets: []
        ),
        ScreenScene.Scene(
            mode: .referencing,
            conversationTurns: [],
            referenceSnippets: ["the workshop runs Tuesday at 9am in room 204 with Dana"]
        ),
    ]

    static let candidates: [String] = [
        "",
        "ok",
        "see you then",
        "are you still coming tonight",
        "still coming tonight",
        "7pm",
        "9am in room 204",
        "quarter past eight",
        "Dana",
        "Priya",
        "the workshop runs Tuesday",
    ]

    /// The recorded shape of one cleaning outcome: what the writer would see
    /// (or why nothing), plus the streaming settlement bit.
    static func signature(_ outcome: CompletionCleanOutcome) -> String {
        switch outcome.result {
        case let .accepted(suggestion):
            return "accepted|\(suggestion.visibleText)|\(outcome.visibleTextIsSettled)"
        case let .rejected(reason):
            return "rejected|\(reason.rawValue)|\(outcome.visibleTextIsSettled)"
        }
    }

    // MARK: - Captured from the pre-refactor cleaner

    /// One signature per (context, raw) pair, in `contexts` x `rawOutputs`
    /// order, recorded from the implementation that tokenized the context on
    /// every call. Any drift here is a visible-output change.
    static let goldenSignatures: [String] = [
        #"rejected|emptyOutput|false"#,
        #"rejected|emptyOutput|false"#,
        #"rejected|noSuggestionSentinel|false"#,
        #"rejected|noSuggestionSentinel|false"#,
        #"accepted| I will try to get back to you|false"#,
        #"accepted| try to get back to you|false"#,
        #"accepted| heading out now|false"#,
        #"accepted| sounds good to me|false"#,
        #"rejected|promptInstructionEcho|false"#,
        #"accepted| let me know if you need anything else|false"#,
        #"accepted| here|false"#,
        #"accepted| let me know|false"#,
        #"accepted| ready. It is not ready|false"#,
        #"accepted| on the way|false"#,
        #"accepted| quoted suggestion here|false"#,
        #"accepted| funeral home is on 5th|false"#,
        #"accepted| going to be a long one|false"#,
        #"rejected|unsafeHiddenOrControlCharacter|true"#,
        #"accepted| a b c d e f g h|true"#,
        #"accepted| ction next week|false"#,
        #"accepted| the quick brown fox jumps|false"#,
        #"rejected|emptyOutput|false"#,
        #"rejected|emptyOutput|false"#,
        #"rejected|noSuggestionSentinel|false"#,
        #"rejected|noSuggestionSentinel|false"#,
        #"accepted| I will try to get back to you|false"#,
        #"accepted| try to get back to you|false"#,
        #"accepted| heading out now|false"#,
        #"accepted| sounds good to me|false"#,
        #"rejected|promptInstructionEcho|false"#,
        #"accepted| let me know if you need anything else|false"#,
        #"accepted| here|false"#,
        #"accepted| let me know|false"#,
        #"accepted| ready. It is not ready|false"#,
        #"accepted| on the way|false"#,
        #"accepted| quoted suggestion here|false"#,
        #"accepted| funeral home is on 5th|false"#,
        #"accepted| going to be a long one|false"#,
        #"rejected|unsafeHiddenOrControlCharacter|true"#,
        #"accepted| a b c d e f g h|true"#,
        #"accepted| ction next week|false"#,
        #"accepted| the quick brown fox jumps|false"#,
        #"rejected|emptyOutput|false"#,
        #"rejected|emptyOutput|false"#,
        #"rejected|noSuggestionSentinel|false"#,
        #"rejected|noSuggestionSentinel|false"#,
        #"accepted|try to get back to you|false"#,
        #"accepted|try to get back to you|false"#,
        #"accepted|heading out now|false"#,
        #"accepted|sounds good to me|false"#,
        #"rejected|promptInstructionEcho|false"#,
        #"accepted|let me know if you need anything else|false"#,
        #"accepted|here|false"#,
        #"accepted|let me know|false"#,
        #"accepted|ready. It is not ready|false"#,
        #"accepted|on the way|false"#,
        #"accepted|quoted suggestion here|false"#,
        #"accepted|funeral home is on 5th|false"#,
        #"accepted|going to be a long one|false"#,
        #"rejected|unsafeHiddenOrControlCharacter|true"#,
        #"accepted|a b c d e f g h|true"#,
        #"accepted|ction next week|false"#,
        #"accepted|the quick brown fox jumps|false"#,
        #"rejected|emptyOutput|false"#,
        #"rejected|emptyOutput|false"#,
        #"rejected|noSuggestionSentinel|false"#,
        #"rejected|noSuggestionSentinel|false"#,
        #"accepted|I will try to get back to you|false"#,
        #"accepted|try to get back to you|false"#,
        #"accepted|heading out now|false"#,
        #"accepted|sounds good to me|false"#,
        #"rejected|promptInstructionEcho|false"#,
        #"accepted|let me know if you need anything else|false"#,
        #"accepted|here|false"#,
        #"accepted|let me know|false"#,
        #"accepted|ready. It is not ready|false"#,
        #"accepted|on the way|false"#,
        #"accepted|quoted suggestion here|false"#,
        #"accepted|funeral home is on 5th|false"#,
        #"accepted|going to be a long one|false"#,
        #"rejected|unsafeHiddenOrControlCharacter|true"#,
        #"accepted|a b c d e f g h|true"#,
        #"accepted|ction next week|false"#,
        #"accepted|the quick brown fox jumps|false"#,
        #"rejected|emptyOutput|false"#,
        #"rejected|emptyOutput|false"#,
        #"rejected|noSuggestionSentinel|false"#,
        #"rejected|noSuggestionSentinel|false"#,
        #"accepted| I will try to get back to you|false"#,
        #"accepted| try to get back to you|false"#,
        #"accepted| heading out now|false"#,
        #"accepted| sounds good to me|false"#,
        #"rejected|promptInstructionEcho|false"#,
        #"accepted| let me know if you need anything else|false"#,
        #"accepted| here|false"#,
        #"accepted| let me know|false"#,
        #"accepted| ready. It is not ready|false"#,
        #"accepted| on the way|false"#,
        #"accepted| quoted suggestion here|false"#,
        #"accepted|eral home is on 5th|false"#,
        #"accepted| going to be a long one|false"#,
        #"rejected|unsafeHiddenOrControlCharacter|true"#,
        #"accepted| a b c d e f g h|true"#,
        #"accepted| ction next week|false"#,
        #"accepted| the quick brown fox jumps|false"#,
        #"rejected|emptyOutput|false"#,
        #"rejected|emptyOutput|false"#,
        #"rejected|noSuggestionSentinel|false"#,
        #"rejected|noSuggestionSentinel|false"#,
        #"accepted|I will try to get back to you|false"#,
        #"accepted|try to get back to you|false"#,
        #"accepted|heading out now|false"#,
        #"accepted|sounds good to me|false"#,
        #"rejected|promptInstructionEcho|false"#,
        #"rejected|emptyAfterPrefixTrimming|false"#,
        #"accepted|here|false"#,
        #"rejected|replaysContext|true"#,
        #"accepted|ready. It is not ready|false"#,
        #"accepted|on the way|false"#,
        #"accepted|quoted suggestion here|false"#,
        #"accepted|funeral home is on 5th|false"#,
        #"accepted|going to be a long one|false"#,
        #"rejected|unsafeHiddenOrControlCharacter|true"#,
        #"accepted|a b c d e f g h|true"#,
        #"accepted|ction next week|false"#,
        #"accepted|the quick brown fox jumps|false"#,
        #"rejected|emptyOutput|false"#,
        #"rejected|emptyOutput|false"#,
        #"rejected|noSuggestionSentinel|false"#,
        #"rejected|noSuggestionSentinel|false"#,
        #"accepted|I will try to get back to you|false"#,
        #"accepted|try to get back to you|false"#,
        #"accepted|heading out now|false"#,
        #"accepted|sounds good to me|false"#,
        #"rejected|promptInstructionEcho|false"#,
        #"accepted|let me know if you need anything else|false"#,
        #"accepted|here|false"#,
        #"accepted|let me know|false"#,
        #"accepted|ready. It is not ready|false"#,
        #"accepted|on the way|false"#,
        #"accepted|quoted suggestion here|false"#,
        #"accepted|funeral home is on 5th|false"#,
        #"accepted|going to be a long one|false"#,
        #"rejected|unsafeHiddenOrControlCharacter|true"#,
        #"accepted|a b c d e f g h|true"#,
        #"accepted|ction next week|false"#,
        #"accepted|the quick brown fox jumps|false"#,
        #"rejected|emptyOutput|false"#,
        #"rejected|emptyOutput|false"#,
        #"rejected|noSuggestionSentinel|false"#,
        #"rejected|noSuggestionSentinel|false"#,
        #"accepted|I will try to get back to you|false"#,
        #"accepted|try to get back to you|false"#,
        #"accepted|heading out now|false"#,
        #"accepted|sounds good to me|false"#,
        #"rejected|promptInstructionEcho|false"#,
        #"accepted|let me know if you need anything else|false"#,
        #"accepted|here|false"#,
        #"accepted|let me know|false"#,
        #"accepted|ready. It is not ready|false"#,
        #"accepted|on the way|false"#,
        #"accepted|quoted suggestion here|false"#,
        #"accepted|funeral home is on 5th|false"#,
        #"accepted|going to be a long one|false"#,
        #"rejected|unsafeHiddenOrControlCharacter|true"#,
        #"accepted|a b c d e f g h|true"#,
        #"accepted|ction next week|false"#,
        #"accepted|the quick brown fox jumps|false"#,
        #"rejected|emptyOutput|false"#,
        #"rejected|emptyOutput|false"#,
        #"rejected|noSuggestionSentinel|false"#,
        #"rejected|noSuggestionSentinel|false"#,
        #"accepted|I will try to get back to you|false"#,
        #"accepted|try to get back to you|false"#,
        #"accepted|heading out now|false"#,
        #"accepted|sounds good to me|false"#,
        #"rejected|promptInstructionEcho|false"#,
        #"accepted|let me know if you need anything else|false"#,
        #"accepted|here|false"#,
        #"accepted|let me know|false"#,
        #"accepted|ready. It is not ready|false"#,
        #"accepted|on the way|false"#,
        #"accepted|quoted suggestion here|false"#,
        #"accepted|funeral home is on 5th|false"#,
        #"accepted|going to be a long one|false"#,
        #"rejected|unsafeHiddenOrControlCharacter|true"#,
        #"accepted|a b c d e f g h|true"#,
        #"accepted|ction next week|false"#,
        #"accepted|the quick brown fox jumps|false"#,
        #"rejected|emptyOutput|false"#,
        #"rejected|emptyOutput|false"#,
        #"rejected|noSuggestionSentinel|false"#,
        #"rejected|noSuggestionSentinel|false"#,
        #"accepted|I will try to get back to you|false"#,
        #"accepted|try to get back to you|false"#,
        #"accepted|heading out now|false"#,
        #"accepted|sounds good to me|false"#,
        #"rejected|promptInstructionEcho|false"#,
        #"accepted|let me know if you need anything else|false"#,
        #"accepted|here|false"#,
        #"accepted|let me know|false"#,
        #"accepted|ready. It is not ready|false"#,
        #"accepted|on the way|false"#,
        #"accepted|quoted suggestion here|false"#,
        #"accepted|funeral home is on 5th|false"#,
        #"accepted|going to be a long one|false"#,
        #"rejected|unsafeHiddenOrControlCharacter|true"#,
        #"accepted|a b c d e f g h|true"#,
        #"accepted|ction next week|false"#,
        #"rejected|replaysContext|true"#,
    ]

    /// One line per (scene, candidate) pair, in `scenes` x `candidates`
    /// order: scene index, echo under the production decision policy, echo
    /// under the tuned 9B policy, unsupported fact under `numbers-and-names`,
    /// unsupported fact under `all-anchors`.
    static let goldenPolicyDecisions: [String] = [
        "0|false|false|false|false",
        "0|false|false|false|false",
        "0|false|false|false|false",
        "0|false|false|false|true",
        "0|false|false|false|true",
        "0|false|false|true|true",
        "0|false|false|true|true",
        "0|false|false|false|true",
        "0|false|false|false|false",
        "0|false|false|false|false",
        "0|false|false|true|true",
        "1|false|false|false|false",
        "1|false|false|false|false",
        "1|false|false|false|false",
        "1|false|false|false|true",
        "1|false|false|false|true",
        "1|false|false|true|true",
        "1|false|false|true|true",
        "1|false|false|false|true",
        "1|false|false|false|false",
        "1|false|false|false|false",
        "1|false|false|true|true",
        "2|false|false|false|false",
        "2|false|false|false|false",
        "2|false|false|false|false",
        "2|true|true|false|false",
        "2|true|false|false|false",
        "2|false|false|false|false",
        "2|false|false|true|true",
        "2|false|false|false|true",
        "2|false|false|false|false",
        "2|false|false|false|false",
        "2|false|false|true|true",
        "3|false|false|false|false",
        "3|false|false|false|false",
        "3|false|false|false|false",
        "3|false|false|false|true",
        "3|false|false|false|true",
        "3|false|false|true|true",
        "3|true|false|false|false",
        "3|false|false|false|true",
        "3|false|false|false|false",
        "3|false|false|false|false",
        "3|true|true|false|false",
    ]
}
