import Foundation

struct HomeMeetingPreviewContent {
    let fallbackText: String
    let transcriptLines: [HomeMeetingTranscriptLine]

    static func make(from markdown: String) -> HomeMeetingPreviewContent {
        let readableLines = readableMarkdownLines(from: markdown)
        return HomeMeetingPreviewContent(
            fallbackText: readableLines.joined(separator: "\n").trimmingCharacters(in: .whitespacesAndNewlines),
            transcriptLines: parseTranscriptLines(readableLines)
        )
    }

    private static func readableMarkdownLines(from markdown: String) -> [String] {
        var lines = markdown.components(separatedBy: .newlines)

        if lines.first?.trimmingCharacters(in: .whitespacesAndNewlines) == "---",
           let endIndex = lines.dropFirst().firstIndex(where: { $0.trimmingCharacters(in: .whitespacesAndNewlines) == "---" }) {
            lines.removeSubrange(...endIndex)
        }

        if let transcriptIndex = lines.firstIndex(where: { line in
            let trimmed = line.trimmingCharacters(in: .whitespacesAndNewlines)
            return trimmed == "## Full Transcript" || trimmed == "## Transcript"
        }) {
            lines = Array(lines.dropFirst(transcriptIndex + 1))
        }

        return lines.filter { line in
            let trimmed = line.trimmingCharacters(in: .whitespacesAndNewlines)
            return trimmed != "---" && !trimmed.hasPrefix("*Generated by Transcripted")
        }
    }

    private static func parseTranscriptLines(_ lines: [String]) -> [HomeMeetingTranscriptLine] {
        var parsed: [HomeMeetingTranscriptLine] = []
        var pending: PendingTranscriptLine?

        func flushPending() {
            guard let current = pending else { return }
            let text = current.textParts
                .joined(separator: " ")
                .trimmingCharacters(in: .whitespacesAndNewlines)
            if !text.isEmpty {
                parsed.append(HomeMeetingTranscriptLine(
                    time: current.time,
                    speaker: current.speaker,
                    text: text
                ))
            }
            pending = nil
        }

        for rawLine in lines {
            let trimmed = rawLine.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty else { continue }

            if let marker = parseTranscriptMarker(trimmed) {
                flushPending()
                pending = PendingTranscriptLine(
                    time: marker.time,
                    speaker: marker.speaker,
                    textParts: marker.remainder.isEmpty ? [] : [marker.remainder]
                )
                continue
            }

            if pending != nil, !isSectionNoise(trimmed) {
                pending?.textParts.append(trimmed)
            }
        }

        flushPending()
        return parsed
    }

    private static func parseTranscriptMarker(_ line: String) -> TranscriptMarker? {
        if line.hasPrefix("**") {
            return parseBoldTimestampMarker(line)
        }
        if line.hasPrefix("[") {
            return parseBracketTimestampMarker(line)
        }
        return nil
    }

    private static func parseBoldTimestampMarker(_ line: String) -> TranscriptMarker? {
        let timeStart = line.index(line.startIndex, offsetBy: 2)
        guard let timeEnd = line[timeStart...].range(of: "**")?.lowerBound else { return nil }
        let time = String(line[timeStart..<timeEnd])
        guard looksLikeTimestamp(time) else { return nil }
        let remainderStart = line.index(timeEnd, offsetBy: 2)
        let remainder = String(line[remainderStart...]).trimmingCharacters(in: .whitespacesAndNewlines)
        return parseSpeakerAndText(time: time, remainder: remainder)
    }

    private static func parseBracketTimestampMarker(_ line: String) -> TranscriptMarker? {
        guard let timeEnd = line.firstIndex(of: "]") else { return nil }
        let time = String(line[line.index(after: line.startIndex)..<timeEnd])
        guard looksLikeTimestamp(time) else { return nil }
        let remainder = line[line.index(after: timeEnd)...].trimmingCharacters(in: .whitespacesAndNewlines)
        return parseSpeakerAndText(time: time, remainder: remainder)
    }

    private static func parseSpeakerAndText(time: String, remainder: String) -> TranscriptMarker {
        var speaker = "Speaker"
        var text = remainder

        if text.hasPrefix("["),
           let speakerEnd = text.firstIndex(of: "]") {
            speaker = cleanSpeaker(String(text[text.index(after: text.startIndex)..<speakerEnd]))
            text = text[text.index(after: speakerEnd)...].trimmingCharacters(in: .whitespacesAndNewlines)
        }

        return TranscriptMarker(time: time, speaker: speaker, remainder: text)
    }

    private static func cleanSpeaker(_ raw: String) -> String {
        raw
            .replacingOccurrences(of: "[[", with: "")
            .replacingOccurrences(of: "]]", with: "")
            .trimmingCharacters(in: .whitespacesAndNewlines)
    }

    private static func looksLikeTimestamp(_ value: String) -> Bool {
        let parts = value.split(separator: ":")
        guard parts.count == 2 || parts.count == 3 else { return false }
        return parts.allSatisfy { !$0.isEmpty && $0.allSatisfy(\.isNumber) }
    }

    private static func isSectionNoise(_ line: String) -> Bool {
        line.hasPrefix("#") || line.hasPrefix("Recorded ")
    }
}

struct HomeMeetingTranscriptLine: Equatable {
    let time: String
    let speaker: String
    let text: String
}

private struct PendingTranscriptLine {
    let time: String
    let speaker: String
    var textParts: [String]
}

private struct TranscriptMarker {
    let time: String
    let speaker: String
    let remainder: String
}
