// AuthCredential.swift
// Represents how Draft authenticates with Anthropic — either an API key
// (from console.anthropic.com) or a subscription token (from `claude setup-token`).
//
// Users with Claude Pro/Max can avoid separate API billing by using
// the token generated by the Claude Code CLI, billed against their subscription.

import Foundation

enum AuthCredential: Sendable {
    /// Standard Anthropic API key from console.anthropic.com.
    /// Uses x-api-key header. Billed per token against API credits.
    case apiKey(String)

    /// OAuth token from `claude setup-token` (Claude Code CLI).
    /// Uses Authorization: Bearer header. Billed against Claude Pro/Max subscription.
    case subscriptionToken(String)

    /// Beta proxy token — routes through draft-proxy Worker.
    /// Uses Authorization: Bearer header. Proxy handles Anthropic auth.
    case betaToken(String)

    // MARK: - Keychain Keys

    static let apiKeyKeychainKey = "anthropic-api-key"
    static let subscriptionTokenKeychainKey = "anthropic-subscription-token"
    static let betaTokenKeychainKey = "draft-beta-token"

    // MARK: - Apply to Request

    /// Sets the correct auth header(s) on an outgoing URLRequest.
    func apply(to request: inout URLRequest) {
        switch self {
        case .apiKey(let key):
            request.setValue(key, forHTTPHeaderField: "x-api-key")
        case .subscriptionToken(let token):
            request.setValue("Bearer \(token)", forHTTPHeaderField: "Authorization")
            // OAuth tokens require the oauth beta flag — without this,
            // the API rejects subscription tokens from non-Claude-Code apps.
            request.setValue("oauth-2025-04-20", forHTTPHeaderField: "anthropic-beta")
        case .betaToken(let token):
            request.setValue("Bearer \(token)", forHTTPHeaderField: "Authorization")
            // No anthropic-beta header needed — the proxy handles Anthropic auth
        }
    }

    // MARK: - Keychain Load/Save/Clear

    /// Load from Keychain — prefers beta token, then API key, then subscription token.
    static func load() -> AuthCredential? {
        #if BETA_BUILD
        if let token = KeychainHelper.load(key: betaTokenKeychainKey) {
            return .betaToken(token)
        }
        #endif
        if let key = KeychainHelper.load(key: apiKeyKeychainKey) {
            return .apiKey(key)
        }
        if let token = KeychainHelper.load(key: subscriptionTokenKeychainKey) {
            return .subscriptionToken(token)
        }
        return nil
    }

    static func saveAPIKey(_ key: String) -> Bool {
        KeychainHelper.delete(key: subscriptionTokenKeychainKey)  // Clear other modes
        KeychainHelper.delete(key: betaTokenKeychainKey)
        return KeychainHelper.save(key: apiKeyKeychainKey, value: key)
    }

    static func saveSubscriptionToken(_ token: String) -> Bool {
        KeychainHelper.delete(key: apiKeyKeychainKey)  // Clear the other mode
        KeychainHelper.delete(key: betaTokenKeychainKey)
        return KeychainHelper.save(key: subscriptionTokenKeychainKey, value: token)
    }

    static func saveBetaToken(_ token: String) -> Bool {
        KeychainHelper.delete(key: apiKeyKeychainKey)
        KeychainHelper.delete(key: subscriptionTokenKeychainKey)
        return KeychainHelper.save(key: betaTokenKeychainKey, value: token)
    }

    static func clear() {
        KeychainHelper.delete(key: apiKeyKeychainKey)
        KeychainHelper.delete(key: subscriptionTokenKeychainKey)
        KeychainHelper.delete(key: betaTokenKeychainKey)
    }

    // MARK: - Display

    var modeName: String {
        switch self {
        case .apiKey: return "API Key"
        case .subscriptionToken: return "Claude Subscription"
        case .betaToken: return "Beta"
        }
    }
}
