// AuthCredential.swift
// Represents how Draft authenticates with Anthropic — either an API key
// (from console.anthropic.com) or a subscription token (from `claude setup-token`).
//
// Users with Claude Pro/Max can avoid separate API billing by using
// the token generated by the Claude Code CLI, billed against their subscription.

import Foundation

enum AuthCredential: Sendable {
    /// Standard Anthropic API key from console.anthropic.com.
    /// Uses x-api-key header. Billed per token against API credits.
    case apiKey(String)

    /// OAuth token from `claude setup-token` (Claude Code CLI).
    /// Uses Authorization: Bearer header. Billed against Claude Pro/Max subscription.
    case subscriptionToken(String)

    // MARK: - Keychain Keys

    static let apiKeyKeychainKey = "anthropic-api-key"
    static let subscriptionTokenKeychainKey = "anthropic-subscription-token"

    // MARK: - Apply to Request

    /// Sets the correct auth header on an outgoing URLRequest.
    func apply(to request: inout URLRequest) {
        switch self {
        case .apiKey(let key):
            request.setValue(key, forHTTPHeaderField: "x-api-key")
        case .subscriptionToken(let token):
            request.setValue("Bearer \(token)", forHTTPHeaderField: "Authorization")
        }
    }

    // MARK: - Keychain Load/Save/Clear

    /// Load from Keychain — prefers API key, falls back to subscription token.
    static func load() -> AuthCredential? {
        if let key = KeychainHelper.load(key: apiKeyKeychainKey) {
            return .apiKey(key)
        }
        if let token = KeychainHelper.load(key: subscriptionTokenKeychainKey) {
            return .subscriptionToken(token)
        }
        return nil
    }

    static func saveAPIKey(_ key: String) -> Bool {
        KeychainHelper.delete(key: subscriptionTokenKeychainKey)  // Clear the other mode
        return KeychainHelper.save(key: apiKeyKeychainKey, value: key)
    }

    static func saveSubscriptionToken(_ token: String) -> Bool {
        KeychainHelper.delete(key: apiKeyKeychainKey)  // Clear the other mode
        return KeychainHelper.save(key: subscriptionTokenKeychainKey, value: token)
    }

    static func clear() {
        KeychainHelper.delete(key: apiKeyKeychainKey)
        KeychainHelper.delete(key: subscriptionTokenKeychainKey)
    }

    // MARK: - Display

    var modeName: String {
        switch self {
        case .apiKey: return "API Key"
        case .subscriptionToken: return "Claude Subscription"
        }
    }
}
