import Foundation
import SwiftUI
import os

// MARK: - TranscriptSummary

/// Metadata for a single speaker parsed from a transcript's YAML frontmatter.
struct SpeakerInfo: Equatable {
    let yamlId: String   // "1", "2" etc. from YAML id field
    let dbId: UUID?      // from YAML db_id field — links to SpeakerDatabase
    let name: String     // current display name ("Speaker 3" or "Jack Trautlein")
}

/// Lightweight parsed representation of a transcript file.
/// Loaded once on init; full content is read lazily only when user taps Copy.
struct TranscriptSummary: Identifiable, Equatable {
    let id = UUID()
    let url: URL
    let title: String
    let date: Date
    let duration: String   // e.g. "47:32"
    let speakerCount: Int
    let speakerNames: [String]  // Parsed from YAML frontmatter
    let timeOfDay: String?      // e.g. "14:30:21" from YAML, nil for old files
    let speakers: [SpeakerInfo] // Structured speaker data for rename UI

    static func == (lhs: TranscriptSummary, rhs: TranscriptSummary) -> Bool {
        lhs.url == rhs.url
    }
}

// MARK: - TranscriptLine

/// A single parsed line from the full transcript section.
/// Used by TranscriptDetailView to render styled transcript content.
struct TranscriptLine: Identifiable {
    let id = UUID()
    let timestamp: String?   // "00:12"
    let speaker: String?     // "Mic/You" or "System/Speaker 1"
    let text: String
}

// MARK: - TranscriptStore

/// Reads transcript .md files from the configured save directory and vends them
/// to TranscriptTrayView. Full file content is read only on copyableText(for:).
@available(macOS 14.0, *)
@MainActor
final class TranscriptStore: ObservableObject {

    @Published var transcripts: [TranscriptSummary] = []

    // MARK: - Init

    init() {
        refresh()
    }

    // MARK: - Public API

    /// Reload transcript list from disk (call after recording completes or on tray open).
    /// File I/O runs off the main thread to avoid blocking the UI.
    func refresh() {
        let dir = saveDirectory
        Task.detached(priority: .userInitiated) {
            guard FileManager.default.fileExists(atPath: dir.path) else {
                if UserDefaults.standard.string(forKey: "transcriptSaveLocation") != nil {
                    AppLogger.pipeline.warning("TranscriptStore: custom save directory not found", ["path": dir.path])
                }
                await MainActor.run { self.transcripts = [] }
                return
            }

            do {
                let files = try FileManager.default
                    .contentsOfDirectory(at: dir, includingPropertiesForKeys: [.creationDateKey], options: [.skipsHiddenFiles])
                    .filter { $0.pathExtension == "md" }
                    .sorted { a, b in
                        let da = (try? a.resourceValues(forKeys: [.creationDateKey]).creationDate) ?? .distantPast
                        let db = (try? b.resourceValues(forKeys: [.creationDateKey]).creationDate) ?? .distantPast
                        return da > db
                    }

                let parsed = files.compactMap { self.parseMetadata($0) }
                await MainActor.run { self.transcripts = parsed }
            } catch {
                AppLogger.pipeline.error("TranscriptStore.refresh failed to read directory", ["path": dir.path, "error": "\(error)"])
                await MainActor.run { self.transcripts = [] }
            }
        }
    }

    /// Returns clean, AI-ready text for a transcript.
    /// Strips YAML frontmatter and the analytics sections so the result can be
    /// pasted directly into Claude, ChatGPT, etc.
    func copyableText(for summary: TranscriptSummary) -> String? {
        guard let raw = try? String(contentsOf: summary.url, encoding: .utf8) else {
            AppLogger.pipeline.error("TranscriptStore.copyableText failed to read file", ["file": summary.url.lastPathComponent])
            return nil
        }

        var content = raw

        // 1. Strip YAML frontmatter (--- … ---)
        if content.hasPrefix("---"),
           let end = content.range(
               of: "\n---\n",
               range: content.index(content.startIndex, offsetBy: 3)..<content.endIndex
           ) {
            content = String(content[end.upperBound...])
        }

        // 2. Jump straight to the "## Full Transcript" section if present
        if let transcriptSection = content.range(of: "## Full Transcript\n") {
            content = String(content[transcriptSection.upperBound...])
        }

        // 3. Drop the trailing footer ("*Generated by…") and stray "---" separators
        let lines = content
            .components(separatedBy: "\n")
            .filter { !$0.hasPrefix("*Generated by") && $0 != "---" }

        let dialogue = lines
            .joined(separator: "\n")
            .trimmingCharacters(in: .whitespacesAndNewlines)

        // 4. Prepend a human-readable header
        let df = DateFormatter()
        df.dateStyle = .full
        df.timeStyle = .none
        let dateStr = df.string(from: summary.date)
        let durationStr = summary.duration.isEmpty ? "" : " | \(summary.duration)"

        return "\(summary.title) — \(dateStr)\(durationStr)\n\n\(dialogue)"
    }

    /// Parse transcript into structured lines for the detail view.
    /// Returns nil if the file can't be read.
    func displayLines(for summary: TranscriptSummary) -> [TranscriptLine]? {
        guard let raw = try? String(contentsOf: summary.url, encoding: .utf8) else {
            AppLogger.pipeline.error("TranscriptStore.displayLines failed to read file", ["file": summary.url.lastPathComponent])
            return nil
        }

        var content = raw

        // 1. Strip YAML frontmatter (--- … ---)
        if content.hasPrefix("---"),
           let end = content.range(
               of: "\n---\n",
               range: content.index(content.startIndex, offsetBy: 3)..<content.endIndex
           ) {
            content = String(content[end.upperBound...])
        }

        // 2. Jump to "## Full Transcript" section if present
        if let transcriptSection = content.range(of: "## Full Transcript\n") {
            content = String(content[transcriptSection.upperBound...])
        }

        // 3. Parse each line
        // Format: [MM:SS] [Source/Speaker] Text
        let linePattern = /^\[(\d{2}:\d{2})\]\s*\[([^\]]+)\]\s*(.+)$/
        var lines: [TranscriptLine] = []

        for rawLine in content.components(separatedBy: "\n") {
            let trimmed = rawLine.trimmingCharacters(in: .whitespaces)
            if trimmed.isEmpty || trimmed.hasPrefix("*Generated by") || trimmed == "---" { continue }

            if let match = trimmed.firstMatch(of: linePattern) {
                lines.append(TranscriptLine(
                    timestamp: String(match.1),
                    speaker: String(match.2),
                    text: String(match.3)
                ))
            } else if !trimmed.hasPrefix("#") && !trimmed.hasPrefix("*") {
                // Non-structured text (rare, but handle gracefully)
                lines.append(TranscriptLine(timestamp: nil, speaker: nil, text: trimmed))
            }
        }

        return lines
    }

    /// Parse a single transcript URL into a summary. Used for re-opening rename UI.
    nonisolated func parseSingle(url: URL) -> TranscriptSummary? {
        parseMetadata(url)
    }

    // MARK: - Save Directory

    private var saveDirectory: URL {
        if let custom = UserDefaults.standard.string(forKey: "transcriptSaveLocation"), !custom.isEmpty {
            return URL(fileURLWithPath: custom)
        }
        let docs = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
        return docs.appendingPathComponent("Transcripted")
    }

    // MARK: - Metadata Parsing

    /// Parse only the metadata needed for the tray row — does NOT load the full transcript.
    /// nonisolated so it can run off the main thread in refresh().
    nonisolated private func parseMetadata(_ url: URL) -> TranscriptSummary? {
        guard let raw = try? String(contentsOf: url, encoding: .utf8) else {
            AppLogger.pipeline.warning("TranscriptStore could not read file", ["file": url.lastPathComponent])
            return nil
        }

        var title = cleanFilenameTitle(url)
        var date: Date = fileCreationDate(url)
        var duration = ""
        var speakerCount = 0
        var speakerNames: [String] = []
        var timeOfDay: String?

        // Parse YAML frontmatter for structured fields
        if raw.hasPrefix("---"),
           let endRange = raw.range(
               of: "\n---\n",
               range: raw.index(raw.startIndex, offsetBy: 3)..<raw.endIndex
           ) {
            let yaml = String(raw[raw.index(raw.startIndex, offsetBy: 4)..<endRange.lowerBound])
            let yamlLines = yaml.components(separatedBy: "\n")
            let yamlQuoteChars = CharacterSet(charactersIn: "\"' ")

            for line in yamlLines {
                let parts = line.split(separator: ":", maxSplits: 1).map {
                    String($0).trimmingCharacters(in: .whitespaces)
                }
                guard parts.count == 2 else { continue }
                let key = parts[0]
                let val = parts[1].trimmingCharacters(in: yamlQuoteChars)

                switch key {
                case "date":
                    let df = DateFormatter(); df.dateFormat = "yyyy-MM-dd"
                    if let d = df.date(from: val) {
                        date = d
                    } else {
                        AppLogger.pipeline.debug("TranscriptStore: malformed date in frontmatter", ["file": url.lastPathComponent, "value": val])
                    }
                case "time":
                    timeOfDay = val
                case "title":
                    if !val.isEmpty {
                        title = val
                    }
                case "duration":
                    duration = val
                case "mic_speakers", "system_speakers":
                    speakerCount += Int(val) ?? 0
                default:
                    break
                }
            }

            var inSpeakersBlock = false
            var currentSpeakerId: String?
            var currentDbId: UUID?
            var currentName: String?
            var speakerInfos: [SpeakerInfo] = []

            func flushCurrentSpeaker() {
                if let id = currentSpeakerId {
                    let name = currentName ?? "Speaker \(id)"
                    speakerInfos.append(SpeakerInfo(yamlId: id, dbId: currentDbId, name: name))
                    if !name.isEmpty && name != "Unknown" && !name.hasPrefix("Speaker ") {
                        speakerNames.append(name)
                    }
                }
                currentSpeakerId = nil
                currentDbId = nil
                currentName = nil
            }

            for line in yamlLines {
                let trimmed = line.trimmingCharacters(in: .whitespaces)
                if trimmed.hasPrefix("speakers:") {
                    inSpeakersBlock = true
                    continue
                }
                if inSpeakersBlock && !line.hasPrefix(" ") && !line.hasPrefix("\t") && !trimmed.isEmpty {
                    flushCurrentSpeaker()
                    inSpeakersBlock = false
                }
                guard inSpeakersBlock else { continue }

                if trimmed.hasPrefix("- id:") {
                    flushCurrentSpeaker()
                    currentSpeakerId = trimmed.replacingOccurrences(of: "- id:", with: "")
                        .trimmingCharacters(in: yamlQuoteChars)
                } else if trimmed.hasPrefix("db_id:") {
                    let raw = trimmed.replacingOccurrences(of: "db_id:", with: "")
                        .trimmingCharacters(in: yamlQuoteChars)
                    currentDbId = UUID(uuidString: raw)
                } else if trimmed.hasPrefix("name:") {
                    currentName = trimmed.replacingOccurrences(of: "name:", with: "")
                        .trimmingCharacters(in: yamlQuoteChars)
                }
            }
            if inSpeakersBlock { flushCurrentSpeaker() }

            // Combine date + time into full datetime for accurate display and sorting
            if let timeStr = timeOfDay {
                let isoDF = DateFormatter()
                isoDF.dateFormat = "yyyy-MM-dd"
                let dateStr = isoDF.string(from: date)
                let dtf = DateFormatter()
                dtf.dateFormat = "yyyy-MM-dd HH:mm:ss"
                if let fullDate = dtf.date(from: "\(dateStr) \(timeStr)") {
                    date = fullDate
                }
            }
        }

        // Prefer a markdown heading title over the filename
        for line in raw.components(separatedBy: "\n") {
            if line.hasPrefix("# ") {
                let candidate = String(line.dropFirst(2)).trimmingCharacters(in: .whitespaces)
                // Skip the generic "Call Recording — …" headings generated by TranscriptSaver
                if !candidate.lowercased().contains("call recording") && !candidate.lowercased().contains("meeting recording") {
                    title = candidate
                }
                break
            }
        }

        return TranscriptSummary(
            url: url,
            title: title,
            date: date,
            duration: duration,
            speakerCount: speakerCount,
            speakerNames: speakerNames,
            timeOfDay: timeOfDay,
            speakers: speakerInfos
        )
    }

    nonisolated private func cleanFilenameTitle(_ url: URL) -> String {
        let name = url.deletingPathExtension().lastPathComponent
        if name.hasPrefix("Call_") { return "Meeting" }
        return name
            .replacingOccurrences(of: "_", with: " ")
            .replacingOccurrences(of: "-", with: " ")
    }

    nonisolated private func fileCreationDate(_ url: URL) -> Date {
        (try? url.resourceValues(forKeys: [.creationDateKey]).creationDate) ?? Date()
    }
}
